### PR TITLE
[lexical-playground] [markdown] Fix: Block math equation is falsely converted to inline equation on MarkdownShortcutPlugin

### LINKED ISSUE #6936: Bug: Block math equation is falsely converted to inline equation on MarkdownShortcutPlugin
Typing an equation like "$$x^2 + y^2 = z^2$$" via "Insert Equation" and then pressing the MarkdownShortcutPlugin changes the equation to inline ($...$).

Lexical version: Current Playground version

## Steps To Reproduce

1. Enter an equation, e.g. "x^2 + y^2 = z^2" via the toolbar (Insert -> Insert Equation) and uncheck "inline".
2. Press the Markdown button

Link to code example: https://playground.lexical.dev/

## The current behavior
Block math equations like "$$...$$" are converted to inline "$...$" when using the   ##MarkdownShortcutPlugin.

## The expected behavior
Block math equations like "$$...$$" should stay the same when using the MarkdownShortcutPlugin.

## Potential Solutions
Possibly quick: A new BLOCK_EQUATION transformer could be added to address the "$$" scenario. [MarkdownTransformers](https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/plugins/MarkdownTransformers/index.ts)
Way more complicated: One might migrate "$, $$" in general to modern LaTex syntax like "\[...\]"

## Impact of fix
Users who rely on markdown capabilities are type safe with equations.

### PR DESCRIPTION
**Pull request by vantage-ola**
Closes #6936

### CODE REVIEW

**Comment by vantage-ola** [comment]
https://github.com/facebook/lexical/issues/6936#issuecomment-2539436779   @etrepum

**Review by etrepum — COMMENTED** [review]
I'm not sure if this is useful or not, but it certainly doesn't fix the bug reported in #6936

**Comment by vantage-ola** [comment]
as of now, i haven't figured out the regex yet. the behaviour of the lexical playground as of now

Uploading Recording 2024-12-18 182216.mp4…

**Comment by etrepum** [comment]
Are you planning to continue working on this, or should it be closed?

**Comment by vantage-ola** [comment]
@etrepum I lost interest. Could not figure out the fix

**Comment by etrepum** [comment]
No worries, thank you for the attempt!

**Pull request closed without merging**
