### PR TITLE
Update TS to 5.1.x

### PR DESCRIPTION
**Pull request by thorn0**

### CODE REVIEW

**Comment by thorn0** [comment]
> @[vercel](https://github.com/apps/vercel) vercel bot [had a problem deploying](https://lexical-41qduuqu8-fbopensource.vercel.app/) to [Preview – lexical](https://lexical-41qduuqu8-fbopensource.vercel.app/) [1 hour ago](https://github.com/facebook/lexical/pull/4695#event-9617481172) Failure

Can't see what went wrong. 404

**Comment by acywatson** [comment]
Something with the docusarus build for the website...

```

[ERROR] Unable to build website for locale en.
--
06:44:03.115 | [ERROR] TypeError: ts.isIdentifierOrPrivateIdentifier is not a function
06:44:03.115 | at isNamedNode (/vercel/path0/node_modules/typedoc/dist/lib/converter/utils/nodes.js:8:13)
06:44:03.115 | at SourcePlugin.onDeclaration (/vercel/path0/node_modules/typedoc/dist/lib/converter/plugins/SourcePlugin.js:70:41)
06:44:03.115 | at triggerEvents (/vercel/path0/node_modules/typedoc/dist/lib/utils/events.js:196:43)
06:44:03.116 | at triggerApi (/vercel/path0/node_modules/typedoc/dist/lib/utils/events.js:167:13)
06:44:03.116 | at eventsApi (/vercel/path0/node_modules/typedoc/dist/lib/utils/events.js:60:18)
06:44:03.116 | at Converter.trigger (/vercel/path0/node_modules/typedoc/dist/lib/utils/events.js:389:13)
06:44:03.116 | at Context.finalizeDeclarationReflection (/vercel/path0/node_modules/typedoc/dist/lib/converter/context.js:140:24)
06:44:03.116 | at Object.convertFunctionOrMethod (/vercel/path0/node_modules/typedoc/dist/lib/converter/symbols.js:239:13)
06:44:03.116 | at convertSymbol (/vercel/path0/node_modules/typedoc/dist/lib/converter/symbols.js:132:41)
06:44:03.117 | at Converter.convertExports (/vercel/path0/node_modules/typedoc/dist/lib/converter/converter.js:146:41)
06:44:03.117 | [INFO] Docusaurus version: 2.0.1
06:44:03.117 | Node version: v16.20.0
06:44:03.149 | npm ERR! Lifecycle script `build` failed with error:
06:44:03.150 | npm ERR! Error: command failed
06:44:03.150 | npm ERR!   in workspace: @lexical/website@0.0.0
06:44:03.150 | npm ERR!   at location: /vercel/path0/packages/lexical-website
06:44:03.162 | Error: Command "npm run build" exited with 1
06:44:03.590 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

```

**Comment by acywatson** [comment]
@thorn0 this is probably good to merge - can you rebase for me to see if we can get the CI passing?

**Comment by thorn0** [comment]
@acywatson I rebased it. Please have a look

**Review by acywatson — APPROVED** [review]

**Pull request merged**
