### PR TITLE
Fixes React TypeScript Element can be had only one child error

### PR DESCRIPTION
**Pull request by MustafaEminn**
TypeScript gives an error when adding two or more children inside of LexicalComposer.

Error: This JSX tag's 'children' prop expects a single child of type 'Element | null', but multiple children were provided.

### CODE REVIEW

**Review by acywatson — APPROVED** [review]
Looks good, thanks!

**Comment by zurfyx** [comment]
LGTM. I wonder, do we need to fix other React TS definitions as well?

**Comment by MustafaEminn** [comment]
We may add JSX.Element[] type to LexicalNestedComposer. What is the difference LexicalComposer and LexicalNestedComposer? I could not find it on the document.

**Comment by zurfyx** [comment]
> We may add JSX.Element[] type to LexicalNestedComposer. What is the difference LexicalComposer and LexicalNestedComposer? I could not find it on the document.

NestedComposer for nested editors, an editor inside an editor. NestedComposer will pass the parent editor to the children editor and inherit some properties like the error handler for you

**Comment by zurfyx** [comment]
Thanks!

**Pull request merged**
