### PR TITLE
Only allow numbers in TablePlugin row / column number input

### PR DESCRIPTION
**Pull request by AlessioGr**
Previously, you were able to input text for the row / column number count.

### CODE REVIEW

**Review by fantactuka — COMMENTED** [review]
Let's pass type prop instead that will be text by default

**Comment by AlessioGr** [comment]
> Let's pass type prop instead that will be text by default

Would you make the type prop optional & text by default if not specified, or required?

**Comment by AlessioGr** [comment]
> Let's pass type prop instead that will be text by default

Good idea - I've updated it!

**Review by zurfyx — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
