### PR TITLE
Symlink config

### PR DESCRIPTION
**Pull request by strdr4605**
This PR aims to clean up the root directory of the repo and make it more appealing to users.

[Keep your JavaScript repository clean](https://strdr4605.com/keep-your-java-script-repository-clean)

See how the repo looks after changes https://github.com/strdr4605/lexical/tree/symlink-config

| Before | After |
| ------- | ----- |
| ![before] | ![after] |

[before]: https://user-images.githubusercontent.com/16056918/163358613-836ff2ef-c37b-45aa-8706-ca4bb6a153d9.png
[after]: https://user-images.githubusercontent.com/16056918/163358703-e2e96cdb-223e-49a8-8fc1-f8214f36cba4.png

By default the `./support/root/` directory is created.
Maybe a good idea is to move `./scripts/` to `./support/scripts/`.

### CODE REVIEW

**Comment by zurfyx** [comment]
Thanks for the contribution! No strong opinions on this PR, I wonder what the rest of the team think about this

**Comment by trueadm** [comment]
I wonder if this break for Windows users?

**Comment by strdr4605** [comment]
> I wonder if this break for Windows users?

Asked a friend to `clone`, `npm install`, and `npm run test-unit`. 
Looks like on Windows you need to run the shell as admin to allow the creation of symlinks.
After this `npm install` and `npm run test-unit` runs as expected.

This might be a small blocker for lexical contributors on windows. But I don't see a big issue here.

**Comment by trueadm** [comment]
Can you re-commit please? I wonder if the CI passes with these changes.

**Comment by strdr4605** [comment]
Also, you can add a README.md in the sourceDir (`./support/root/README.md`) and it will be excluded from symlink. Where you can explain if needed, why config files stay in `./support/root/`.

**Comment by trueadm** [comment]
Please can you trigger another update on this so the CI can actually run (maybe with a rebase)? I think this PR was put up before we fixed the detection mechanism somehow. Sorry!

**Comment by strdr4605** [comment]
@zurfyx, @trueadm, can you approve the workflow to run to see if the issue disappeared after [Symlink-config after npm ci](https://github.com/facebook/lexical/pull/1713/commits/082daa51437d4793278c0f0b13f404176993a300)?!

**Comment by acywatson** [comment]
Hey @strdr4605 - thanks for submitting this. We discussed this as a team and we'd prefer to keep the current configuration for now. We may revisit this again in the future.

**Pull request closed without merging**
