### PR TITLE
Remove spaces from clipboard html

### PR DESCRIPTION
**Pull request by mmarkelov**
Some investigation on https://github.com/facebook/lexical/issues/1988

This is because copied html contains line breakers, which lexical convert to TextNode. I guess that `htmlString` should be inline, without any breakers

### CODE REVIEW

**Comment by fantactuka** [comment]
Full clean up of \n's might be a bit too much (e.g. might want to keep it within `<pre>`). Also not sure about ` {2}` part - if trying to remove duplicated spaces you'd still want to keep at least one: `hello _ _ _ world` -> `hello _ world`.

@acywatson @tylerjbainbridge WDYT about this one, should tabs/empty lines be cleaned up upfront on on node level

**Comment by tylerjbainbridge** [comment]
> Full clean up of \n's might be a bit too much (e.g. might want to keep it within `\<pre\>`). Also not sure about ` {2}` part - if trying to remove duplicated spaces you'd still want to keep at least one: `hello _ _ _ world` -> `hello _ world`.
> 
> @acywatson @tylerjbainbridge WDYT about this one, should tabs/empty lines be cleaned up upfront on on node level

Definitely agree re: duplicated spaces, I personally don't like the idea of additional spaces being lost upon saving because they're most likely there for a reason.

And regarding `/n`- we're just using the browser's native `innerHtml` serialization to build the string and like Maksim said there may be some cases where the `/n`s are important like within `<pre>` tags or text.

I think this should be handled in the `$generateNodesFromDOM(...)` function and just avoid creating unnecessary text nodes for line breaks.

**Comment by mmarkelov** [comment]
@tylerjbainbridge @fantactuka I tried to put this logic into `$generateNodesFromDOM(...)`, but this is a challenge for me. I understood that removing the whole spaces was not a good idea. But what if we remove new lines only between tags, i guess it should work. What do you think guys?
https://regex101.com/r/MXqZMS/1

**Comment by fantactuka** [comment]
> @tylerjbainbridge @fantactuka I tried to put this logic into `$generateNodesFromDOM(...)`, but this is a challenge for me. I understood that removing the whole spaces was not a good idea. But what if we remove new lines only between tags, i guess it should work. What do you think guys? https://regex101.com/r/MXqZMS/1

It's a better approach, but it yet gonna fall short for `<pre>` tag :( Looked a bit more into in and Tyler's suggestion around `$generateNodesFromDOM` makes sense, or even more specific `$createNodesFromDOM` where DOM node transformed into lexical node. E.g. you can check if current element tag is PRE and keep text nodes with `\n` content, or skip them otherwise. Do you want to give another try or I can take over it?

**Comment by mmarkelov** [comment]
@fantactuka thanks for your report. IDK, but shouldn't it be the part of `LexicalTextNode`?
Maybe here:
```js
function convertTextDOMNode(domNode: Node): DOMConversionOutput {
  return {node: domNode.textContent.match(/\n+/g) ? null : $createTextNode(domNode.textContent)};
}
```

**Comment by trueadm** [comment]
Can we confirm we still need this? I noticed lately this has already improved?

**Comment by fantactuka** [comment]
#2431 fixing this issue newlines, while preserving it within `<pre>`

**Pull request closed without merging**
