### PR TITLE
Remove duplicate declaration

### PR DESCRIPTION
**Pull request by aMoRRoMa**
I faced it after the latest release. A quick fix that removes duplication.

### CODE REVIEW

**Comment by thorn0** [comment]
It really has two parameters. E.g. see https://lexical.dev/docs/concepts/dom-events#1-event-delegation
I think they just should be renamed.

**Comment by acywatson** [comment]
> It really has two parameters. E.g. see https://lexical.dev/docs/concepts/dom-events#1-event-delegation I think they just should be renamed.

Yea, this is right. currentRoot, prevRoot should work.

**Comment by aMoRRoMa** [comment]
> It really has two parameters. E.g. see https://lexical.dev/docs/concepts/dom-events#1-event-delegation I think they just should be renamed.

Oh, I see. So, I'll rename them to make it not confusing.

**Comment by aMoRRoMa** [comment]
@acywatson @thorn0 Please take a look again

**Pull request merged**
