### PR TITLE
Check for ParagraphNode instance rather than type

### PR DESCRIPTION
**Pull request by moy2010**
Fix for displaying placeholder for custom nodes

### CODE REVIEW

**Comment by trueadm** [comment]
You can if use $isParagraphNode instead. It’s imported from Lexical.

**Comment by moy2010** [comment]
> You can if use $isParagraphNode instead. It’s imported from Lexical.

Fixed!

**Review by trueadm — APPROVED** [review]

**Comment by acywatson** [comment]
You'll need to rebase onto main to fix that failing integrity check - I  just merged the fix in

**Comment by moy2010** [comment]
> You'll need to rebase onto main to fix that failing integrity check - I just merged the fix in

@acywatson, unfortunately I had created this PR from the browser, so I couldn't rebase any changes from main. I have now cloned the repo locally and created a new PR (#3557).

**Comment by moy2010** [comment]
Closed in favor of #3557

**Pull request closed without merging**
