### PR TITLE
added sanitizer to createDOM and updateDOM in lexical/link

### PR DESCRIPTION
**Pull request by heesungjang**
issue: [[#2806](https://github.com/facebook/lexical/issues/2806)]

- added urlSanitizer to createDOM and updateDOM in lexical/linkNode with default allowed protocols(safe url protocols)

### CODE REVIEW

**Comment by trueadm** [comment]
This is a lot of code to be added to, what is meant to be, a lightweight node that is more of a "store" in this sense. I'd expect the sanitization to occur at time of entry, and definitely not on when rendering to the DOM. On a traditional website, you'd sanitize the URL before you store it in a database, and I'd expect the same thing here.

Can we move this logic to the input on the link editor for the playground instead maybe?

**Comment by acywatson** [comment]
> 

@heesungjang 

Sorry, this is basically what you already did in the previous pull request. We are having some internal debate over where the correct place to put this logic is and what the responsibility of Lexical should be wrt to sanitizing anchor hrefs.

**Comment by heesungjang** [comment]
@acywatson Thanks ok!! I am learning a lot through this. Please let me know if any updates!

**Comment by acywatson** [comment]
> @acywatson That's ok!! Please let me know if any updates!

Thanks for your patience here - we decided we want to take the approach in your first PR for now. I reopened that:

https://github.com/facebook/lexical/pull/2825

Once the checks pass, we can merge it!

Thanks for contributing!

**Comment by heesungjang** [comment]
> @acywatson That's ok!! Please let me know if any updates!

Thanks for your patience here - we decided we want to take the approach in your first PR for now. I reopened that:

https://github.com/facebook/lexical/pull/2825

Once the checks pass, we can merge it!

Thanks for contributing!

Thanks for the reply! I just wanted to clarify that the "checks" you mentioned are the test scripts or is there anything I have to further modify in the code?

**Comment by acywatson** [comment]
> > @acywatson That's ok!! Please let me know if any updates!
> > Thanks for your patience here - we decided we want to take the approach in your first PR for now. I reopened that:
> > #2825
> > Once the checks pass, we can merge it!
> > Thanks for contributing!
> 
> Thanks for the reply! I just wanted to clarify that the "checks" you mentioned are the test scripts or is there anything I have to further modify in the code?

Yep, just the tests. Thanks again for contributing!

**Pull request closed without merging**
