### PR TITLE
Added improved type safety for Lexical Composer and fixed documentation error

### PR DESCRIPTION
**Pull request by Legonois**
## Description

Added extra type safety for the Lexical Composer!

When writing code before, there was a way to include properties that don't exist on the object

image

This allows typeos...

> *such as defining editorState and EditorState and spending a few hours debugging what went wrong between projects and finally figuring it out because it was a simple type safety error*

After proposed changes, it allows typescript to give errors because of the defined properties. Basically implicitly applies `InitialConfigType` to any config passed to the LexicalComposer

```tsx

export type InitialConfigType = Readonly<{
  editor__DEPRECATED?: LexicalEditor | null;
  namespace: string;
  nodes?: ReadonlyArray<Klass<LexicalNode> | LexicalNodeReplacement>;
  onError: (error: Error, editor: LexicalEditor) => void;
  editable?: boolean;
  theme?: EditorThemeClasses;
  editorState?: InitialEditorStateType;
  html?: HTMLConfig;
}>;

const InitialConfig: InitialConfigType = { // The added type
  namespace: 'test',
  onError: (error: Error, editor: LexicalEditor) => {
    console.error(error)},
}

```

### Examples of errors emitted after fix!

image

image

This doesn't close an issue, as I had just been working on this on my own

ALSO fixed a missing curly brace found in the documentation

### CODE REVIEW

**Comment by etrepum** [comment]
Did you try changing `type` to `interface` first? It's not as complete of a solution but TypeScript is generally a lot better at reporting mistakes when you are using `interface` (and it's often more performant too). I have a feeling that the codebase is using `type` mostly because it's similar to the flow way of doing things rather than an intentional choice.

**Comment by Legonois** [comment]
@etrepum 

Using interface does not seem to fix the type error

```tsx
// type Impossible<K extends keyof any> = {
//   [P in K]: never;
// };

// type NoExtraProperties<T, U extends T = T> = U & Impossible<Exclude<keyof U, keyof T>>;

export type InitialEditorStateType =
  | null
  | string
  | EditorState
  | ((editor: LexicalEditor) => void);

export interface InitialConfigType {
  editor__DEPRECATED?: LexicalEditor | null;
  namespace: string;
  nodes?: ReadonlyArray<Klass<LexicalNode> | LexicalNodeReplacement>;
  onError: (error: Error, editor: LexicalEditor) => void;
  editable?: boolean;
  theme?: EditorThemeClasses;
  editorState?: InitialEditorStateType;
  html?: HTMLConfig;
}

// type Props<T extends NoExtraProperties<InitialConfigType>> = React.PropsWithChildren<{
//   initialConfig: T  & Impossible<Exclude<keyof T, keyof InitialConfigType>>;
// }>;

type Props = React.PropsWithChildren<{
  initialConfig: InitialConfigType;
}>;

export function LexicalComposer({
  initialConfig, 
  children
}: Props): JSX.Element {
```

Does not display an error

image

**Comment by etrepum** [comment]
does it give you an error if you specify it as a literal inline in the jsx, or if you provide an explicit type annotation for the variable?

**Comment by etrepum** [comment]
Closing this PR due to staleness! If there are new updates, please reopen the PR.

**Pull request closed without merging**
