### PR TITLE
Add inline plugin example for images 

### PR DESCRIPTION
**Pull request by akmarzhan1**
- [x] added a new subpage for the images example in the playground (under “/images-demo”)
- [x] added a new page and the example on the website (under “Demos”)

Issue [#2886](https://github.com/facebook/lexical/issues/2886)

Might be possible issues with cross-origin access (now I am embedding a page that doesn't exist yet in the playground, but the embed is blocked when trying for the main playground).

### CODE REVIEW

**Comment by akmarzhan1** [comment]
I am not sure why the website deployment is failing, but I am guessing that it is because docusaurus v1 doesn't support react-router v6. I had some issues with react-router versions (v5 and v6) and docusaurus initially but they got fixed after I updated docusaurus on my computer (npm installs v1 and not v2). The package.json already had docusaurus v2 so I don't know what to fix.

**Comment by thegreatercurve** [comment]
@akmarzhan1 The reason you're getting the 404 locally is because your `iframe` attribute of `src` is pointing at the production, `http://playground.lexical.dev/image-demo/`, when the new page in this PR hasn't been deployed yet.

My recommendation would be to move all of the changes you've made in `packages/lexical-playground`, and then to add your Image plugin app into `packages/lexical-website/src/pages/examples/image` instead. 

Remove all of the usages of React Router, as Docusaurus has its own router, and then export your `ImagePlayground` as the main component from this page.

Then, in `packages/lexical-website/docs/demos/advanced-examples/images` point your iframe `src` to a relative URL of wherever you host your images demo (e.g. `src="/demos/image"`) and it should appear even in local development.

Something like the below.

image

Does that sort of make sense?

**Comment by akmarzhan1** [comment]
Thanks for the feedback! The 404 error was on purpose because I couldn't find a way to embed the playground without errors. 

Just to clarify, does this mean I should revert the playground to its original state (remove all the changes) and instead add the image plugin app fully to the website?

**Comment by thegreatercurve** [comment]
> Thanks for the feedback @thegreatercurve! The 404 error was on purpose because I couldn't find a way to embed the playground without errors. 
> 
> Just to clarify, does this mean I should revert the playground to its original state (remove all the changes) and instead add the image plugin app fully to the website?

Yeah, that's right. That should be a lot simpler than having to wrestle with the playground as well. Everything will just be handled by the same router

**Comment by akmarzhan1** [comment]
> Yeah, that's right. That should be a lot simpler than having to wrestle with the playground as well. Everything will just be handled by the same router

Makes sense. I will try to do that and will let you know if I have any questions.

**Comment by akmarzhan1** [comment]
@thegreatercurve I created a new PR draft (I figured it would be easier to create a new branch since I needed to revert all the changes to the playground), here is the link: https://github.com/facebook/lexical/pull/3216

**Pull request closed without merging**
