### PR TITLE
Fix character styles position + caret color

### PR DESCRIPTION
**Pull request by trueadm**
Fixes https://github.com/facebook/lexical/issues/2079.

### CODE REVIEW

**Review by zurfyx — APPROVED** [review]

**Comment by NicolasRoelandt** [comment]
I am not sure I understand how this fixes https://github.com/facebook/lexical/issues/2079. I've just tried to apply the changes to https://github.com/facebook/lexical/compare/main...caret-issue and the issue is still there.

**Comment by trueadm** [comment]
@NicolasRoelandt It fixes the issue by not setting the caret-color, meaning the content editable cusor color will correctly that of the content editable. In your issue, it looks like you're apply a style to the text node. Given there is no text node when the paragraph is empty, how can it inherit the color? Try setting the color on the content editable itself.

**Comment by trueadm** [comment]
@NicolasRoelandt I'm struggling to understand the exact problem here. This is working as intended, and is consistent with how other web text editors work (I checked Google Docs, Quip and ProseMirror).

If you're on an empty paragraph, the inherited cursor color should always be that of the parapgrah, as the selection point inherits that of the paragraph, given there is no text. When you have text content, selection moves to the text, rather than the paragraph and thus takes the cursor color from the text color of the text node.

So you shouldn't need to be trying to keep the text.base color in sync with the caret color, as you should never be setting the text color in `text.base`. In fact, I'm not even sure why we have `text.base`, we should get rid of it.

**Comment by NicolasRoelandt** [comment]
@trueadm 
> I checked Google Docs, Quip and ProseMirror
I see. In Quip, if I change the text color the caret changes only once I start typing. But I feel it's a bit of a different scenario where the color is given by the user and not by the surface itself.

> as you should never be theming the text color in text.base. In fact, I'm not even sure why we have text.base, we should get rid of it.

This probably makes sense, as the color should be set in the content editable styles. I am just trying to think if there are styles you might want to apply **only** to text nodes and not to anything else

**Pull request merged**
