### PR TITLE
Auto focus the text when markdown import got match of none

### PR DESCRIPTION
**Pull request by aquarius-wing**
# Background
Fix the issue #4474 
# Cause of Problem
The text is focused only when the markdown transformer matched
But when it doesn't the auto focus feature was lost after the [commit](https://github.com/aquarius-wing/lexical/commit/e817a55a94522c98103401a2620a179cd110b548) was release
# The logic in deep 
1. the markdown transformer matched
2. the lexical getSelection is not null
3. so in commit link above, it can run `root.selectEnd`

So if I want `root.selectEnd` be run, I must make lexical has selection.
That's the why I wrote the code in this PR

### CODE REVIEW

**Comment by fantactuka** [comment]
The point of that [commit](https://github.com/aquarius-wing/lexical/commit/e817a55a94522c98103401a2620a179cd110b548) is to call "select" only if selection was non-null before. With the suggested change, it'll always call select() if some markdown conversion happened.

**Comment by aquarius-wing** [comment]
I believe that regardless of whether the markdown transformer matches or not, the editor should be focused.
Otherwise, it may cause confusion as it sometimes focuses and sometimes does not.

**Comment by fantactuka** [comment]
> I believe that regardless of whether the markdown transformer matches or not, the editor should be focused. Otherwise, it may cause confusion as it sometimes focuses and sometimes does not.

Not really, running markdown import does not require editor to be focused and does not mean user need it to be focused. E.g., imagine page for blog post editing with title (input[type=text]) and content field (lexical). When markdown for content is loaded and populated to lexical, user might still want to have focus on title field

**Comment by aquarius-wing** [comment]
So I should delete the line in 
[node.select(0, 0);](https://github.com/facebook/lexical/blob/a82b7547ea158a5472afda0f702ed844ca25fd0a/packages/lexical-markdown/src/MarkdownTransformers.ts#L93)?

**Pull request closed without merging**
