### PR TITLE
Fix: dropdown misplacement after scrolling

### PR DESCRIPTION
**Pull request by paigekim29**

### CODE REVIEW

**Comment by ivailop7** [comment]
Could we get a before and after on this and some description please, I'm unable to reproduce what the issue is.

**Review by ivailop7 — APPROVED** [review]

**Comment by ivailop7** [comment]
Actually, ignore my approval of this one. Trying this in the Preview Link, it makes things worse than they are right now. if have long text and have scrolled down and then open a dropdown, the dropdown is rendered with scroll offset in the middle of the screen vs at the end of the toolbar height. This PR doesn't seem to be fixing anything. Could you provide an example the issue this PR is meant to be fixing?

**Review by ivailop7 — CHANGES_REQUESTED** [review]
As per previous comment

**Comment by paigekim29** [comment]
@ivailop7 I have created a new PR https://github.com/facebook/lexical/pull/5443. I believe that `position:fixed` is causing an issue after scrolling.

**Comment by ivailop7** [comment]
> @ivailop7 I have created a new PR #5443. I believe that `position:fixed` is causing an issue after scrolling.

why the separate PR, instead of updating this one?

**Comment by paigekim29** [comment]
@ivailop7 I updated it as you recommended, so please check the video for the changes

## Before
- After adding extensive content to the editor, I inserted a table. However, the dropdown for Table Action doesn't appear at all. Upon inspecting the console, it was evident that the dropdown, located at the bottom of the page, fails to display.
https://github.com/facebook/lexical/assets/70982342/4e2168c8-a862-451b-a7ce-8ef478f05390

## After
- Modifying the dropdown CSS and adjusting the top position of the TableActionMenuPlugin dropdown resolved the issue.
https://github.com/facebook/lexical/assets/70982342/64a1134d-db77-44b1-b62f-4c1a57b78537

**Comment by zurfyx** [comment]
Can we please look into the failing tests and/or rebase?

**Comment by paigekim29** [comment]
will look into it and request after fix

**Pull request closed without merging**
