### PR TITLE
Fix: fixes regex in YouTube AutoEmbedPlugin

### LINKED ISSUE #4887: Bug: Incorrect URL Recognition in YouTube AutoEmbedPlugin
The YouTube AutoEmbedPlugin seems to incorrectly recognize and try to embed non-YouTube URLs. Specifically, I noticed this behavior when I tried using the URL https://github.com/vietanhdev/anylabeling. While I expect the plugin not to consider this as a valid YouTube link, it appears to be treating it as one.

Lexical version: 0.11.1

## Steps To Reproduce

1. copy and paste the URL(`https://github.com/vietanhdev/anylabeling`).
2. you will see Youtube AutoEmbedPlugin activated.

Link to code example:

image

## The current behavior
The YouTube AutoEmbedPlugin attempts to embed the provided GitHub URL, presumably recognizing it as a valid YouTube link.

## The expected behavior
The plugin should not recognize non-YouTube URLs (like the GitHub URL in question) as valid YouTube links and should not attempt to embed them.

### PR DESCRIPTION
**Pull request by k-rajat19**
Resolves #4887

### CODE REVIEW

**Review by fantactuka — APPROVED** [review]
LG!

**Comment by k-rajat19** [comment]
@fantactuka could this be merged?

**Comment by acywatson** [comment]
@ivailop7 multiple tests are failing including YouTube embed related ones, from what I see. Can we please revert or roll forward a fix?

**Comment by ivailop7** [comment]
> > > @ivailop7 multiple tests are failing including YouTube embed related ones, from what I see. Can we please revert or roll forward a fix?
> > 
> > 
> > I saw them, but they seemed like the 'standard' test failures. Will revert.
> 
> There generally shouldn't be failures on retry outside of Linux collab tests, AFAIK

I've noticed sporadic failures on Mac and Windows as well, raised the revert commit.

**Pull request merged**
