### PR TITLE
fix mutate with replace klass

### PR DESCRIPTION
**Pull request by Piechota**
When registering mutation check for Node that replaced original one.
_mutation_ are a map so only one entry.

Should fix  [#4498](https://github.com/facebook/lexical/issues/4498#issue-1709961845)

### CODE REVIEW

**Comment by etrepum** [comment]
This looks like it solves the same problem as #6076 so it should close that as well if this PR is chosen. My review comments would be basically the same: https://github.com/facebook/lexical/pull/6076#pullrequestreview-2051214716

**Comment by etrepum** [comment]
I think this approach is probably better, but without really any docs or test coverage it's hard to say if there are any additional caveats to this simpler solution

**Comment by Piechota** [comment]
In that other PR you have a good point about chain of node replacements.
Currently this code doesn't support it, I will fix it when I have a second.

**Comment by Piechota** [comment]
So I have added loop to support multilevel replacement.
But I have problem testing it, it seems like right now it isn't supported really well. 
I think we should also loop over _replace_ in $applyNodeReplacement()
But that's for different change.

**Comment by etrepum** [comment]
Good idea, it seems that there is a lack of test coverage all around for this corner of the API!

**Comment by StyleT** [comment]
If no-one picks this up - I'll look at it later to add some tests. I touched klasses already in the devtools

**Comment by aleksandr-lapushkin** [comment]
> If no-one picks this up - I'll look at it later to add some tests. I touched klasses already in the devtools

That would be very welcome! I'll close https://github.com/facebook/lexical/pull/6076 since this one seems more in line with expectations.

**Comment by StyleT** [comment]
Closed in favor of https://github.com/facebook/lexical/pull/6189 (tests added)

**Pull request closed without merging**
