### PR TITLE
renamed character styles popup plugin

### PR DESCRIPTION
**Pull request by harish-sethuraman**
Addressing  
- https://github.com/facebook/lexical/issues/2446

I felt like `FloatingFormatter` seemed like a better name. Feel free to suggest other names if any. 😅

### CODE REVIEW

**Comment by zurfyx** [comment]
Well, `FloatingToolbar` is the only one that returns proper results when Googling -> https://www.google.com/search?q=floating+toolbar

Also, appreciate you're taking this! If you want you make as well rename some similar wording inside this file like:
- useCharacterStylesPopup
- FloatingCharacterStylesEditor

**Comment by harish-sethuraman** [comment]
`character-style-popup` should I rename styles too?

**Comment by zurfyx** [comment]
> `character-style-popup` should I rename classnames and styles too?

That would be awesome. Also, @thegreatercurve just suggested `TextFormatFloatingToolbar`, I quite like that one, WDYT?

**Comment by harish-sethuraman** [comment]
TextFormatFloatingToolbar -> `FloatingTextFormatToolbar` may be? It would be easy to grasp if floating was at the start?

**Comment by zurfyx** [comment]
> TextFormatFloatingToolbar -> `FloatingTextFormatToolbar` may be? It would be easy to grasp if floating was at the start?

Prob won't make a different when you search via CMD + P but no strong opinions on this!

**Review by zurfyx — APPROVED** [review]
Thank you!

**Pull request merged**
