### PR TITLE
Unbullet one list item not the whole list

### LINKED ISSUE #5039: Bug: Toggling the list item is not working properly
When the text is highlighted and the user tries to remove the numbered/ bullet points from any specific word it automatically removes the numbered/ bullet points from other points too

https://github.com/facebook/lexical/assets/127859730/0da13777-55f4-416a-bd32-82d0d33f9ebc

Lexical version:

## Steps To Reproduce

1.Create a list with items
2. Try to remove the bullet or number list from the middle item
3. It will remove all the bullet or number list items

Link to code example: [lexical.](https://playground.lexical.dev/)

## The current behavior

When the text is highlighted and the user tries to remove the numbered/ bullet points from any specific word it automatically removes the numbered/ bullet points from other points too

## The expected behavior

It should only remove the selected bullet/number element

### PR DESCRIPTION
**Pull request by ivailop7**
Before

https://github.com/facebook/lexical/assets/7893468/65dd9a8c-45f6-435a-a002-1c6232e41150

After

https://github.com/facebook/lexical/assets/7893468/654e5111-c84b-4b2e-8fd1-3f95690f984f

Fixes #5039

### CODE REVIEW

**Comment by acywatson** [comment]
Nice! I'm really surprised this works, as we have a bunch of logic in the lists module to split the lists in various nesting situations. I wonder if this means we can get rid of that stuff, if setBlocksType is handling it well...

**Review by zurfyx — DISMISSED** [review]
Nice! As Acy indicated, I wonder if we can simplify the lists code.

Besides that, would be nice to have an external module to share toolbar code so that we don't have to replicate the fixes elsewhere now, I'll put it on our shared list

**Comment by acywatson** [comment]
Looks like we still do have 3 lists tests consistently failing

**Comment by ivailop7** [comment]
will look into this again over the weekend

**Comment by ivailop7** [comment]
@acywatson tests fixed

**Review by acywatson — APPROVED** [review]

**Pull request merged**
