### PR TITLE
support for onclickoutside of excalidraw modal

### PR DESCRIPTION
**Pull request by siva-kannan3**
Addresses this issue [1927](https://github.com/facebook/lexical/issues/1927).

### CODE REVIEW

**Review by zurfyx — COMMENTED** [review]
Thank you for taking a stab on the modal! While your implementation is valid it may need some tweaks:

1. Events outside the modal shouldn't trigger instantly
2. It helps user retain the focus if they can the background visually darkened

Hence, I propose a version that's closer to - https://www.w3schools.com/howto/howto_css_modals.asp

A background div with some opacity and a content modal (like the current). When you click outside the content the modal disappears and the first click handles closing the modal.

**Comment by siva-kannan3** [comment]
@zurfyx I have added the background overlay for excalidraw modal as mentioned in the second point.
Can you explain the first point a bit detail ?

**Comment by zurfyx** [comment]
Thanks! What you have makes sense now. Happy to merge as-is but we'll probably need some follow up PRs on a discard modal once you click outside as it's easy to accidentally lose content.

Actually, I even wonder whether we need save/discard action buttons, perhaps it should (always) be automatically saved. @rulikrulit thoughts on this?

**Review by zurfyx — APPROVED** [review]
Mind rebasing/merging with main and see if the E2E test failures still persist?

**Pull request merged**
