### PR TITLE
Fix bug 3535

### PR DESCRIPTION
**Pull request by lizhu68**
Sorry, this is my first PR, I think I didn't line it up with the bug I created earlier - https://github.com/facebook/lexical/issues/3535

I have tested the suggested changes locally and it works as expected.

Sorry for the confusion

### CODE REVIEW

**Comment by trueadm** [comment]
Please can you sign the CLA?

**Comment by lizhu68** [comment]
I submitted 2 hours ago, not sure why it's not updated, I just did it again
image

**Comment by jurajh-fb** [comment]
Apologies for the CLA issue - we've had a regression over the weekend and checked in a fix this morning that's slowly making its way through the system. I'm running the process manually right now to unblock you. The issue should be resolved going forward by the end of the day. Thank you for being patient.

**Review by trueadm — APPROVED** [review]

**Comment by lizhu68** [comment]
Thanks so much for the quick approval and merge. May I know when it will be released?

**Pull request merged**
