### PR TITLE
Add conversion functions for span and br elements to CodeNode

### LINKED ISSUE #3976: Bug: Pasting Code elements in a CodeBlock replaces it
When code text that doesn't follow the existing covered cases (i.e. importing a `code` html element or a `div` element with a `monospace` font-family) is pasted, the code block is replaced by a paragraph.

Here's an example of html with a format that isn't covered:

```
<div dir="ltr">
   <span style="font-family:monospace">
      <span style="color:rgb(0,0,0)">[diff]
      </span><br> &nbsp;&nbsp;&nbsp;tool = meld
      <br>[difftool]
      <br> &nbsp;&nbsp;&nbsp;prompt = false
      <br>[difftool "meld"]
      <br> &nbsp;&nbsp;&nbsp;cmd = meld "$LOCAL" "$REMOTE"
      <br>[merge]
      <br> &nbsp;&nbsp;&nbsp;tool = meld
      <br>[mergetool "meld"]
      <br> &nbsp;&nbsp;&nbsp;cmd = flatpak run org.gnome.meld "$LOCAL" "$BASE" "$REMOTE" --output "$MERGED"
      <div class="yj6qo"></div>
      <div class="adL"><br></div>
   </span>
</div>
```

Lexical version: 0.8.0

## Steps To Reproduce

1. Copy the text from an html file that follows the example above.
2. Create a new code block (i.e. with triple backticks).
3. Paste the copied text.

## The current behavior

The copied text is transformed into a paragraph, and the code block is removed.

## The expected behavior

The copied text is pasted into the code block

### PR DESCRIPTION
**Pull request by moy2010**
Add conversion functions for span and br elements to CodeNode.

Fix #3976

### CODE REVIEW

**Comment by moy2010** [comment]
Hey, Lexical team! In this PR I added conversion functions for `span` and `br` elements, but the issue with thisis that the text from the clipboard is transformed into many `CodeNode` elements.

In `clipboard.ts` I tried to collapse all of them into one (check the code commented out), but didn't work as expected, so I decided to push the PR to get feedback from you.

**Comment by moy2010** [comment]
The conversion function for the `span` element is also breaking some unit tests :/. I thought that returning null would allow other conversion functions to step in...

**Comment by acywatson** [comment]
> I thought that returning null would allow other conversion functions to step in...

Ah, yea -this is a bit confusing. If you want to allow other handlers to run, you have to return null from the functions in the map returned by importDOM. So it'd be like:

```
class CodeNode extends ElementNode {
...
static importDOM(): DOMConversionMap | null {
  return {
    ...
    table: (node: Node) => {
      if (isGitHubCodeTable(node as HTMLTableElement)) {
        return {
          conversion: convertTableElement,
          priority: 3,
        };
      }
      return null;
    },
    ...
  };
}
...
}
```

**Comment by moy2010** [comment]
> > I thought that returning null would allow other conversion functions to step in...
> 
> Ah, yea -this is a bit confusing. If you want to allow other handlers to run, you have to return null from the functions in the map returned by importDOM.

Ah, gotcha! I have updated the PR with this fix so that the unit tests don't break. I still have to work on collapsing all the code nodes into one.

**Comment by zurfyx** [comment]
Can we look into the failing E2E tests please?

**Review by zurfyx — CHANGES_REQUESTED** [review]
Can we look into the failing E2E tests please?

**Comment by thegreatercurve** [comment]
Closing due to PR becoming stale

**Pull request closed without merging**
