### PR TITLE
Overflow of logos of action items in Lexical Playground

### LINKED ISSUE #4095: Bug: Overflow of logos of action items in Lexical Playground.
Link to code example: https://playground.lexical.dev/

## The current behavior
image

## The expected behavior
image

### PR DESCRIPTION
**Pull request by gaurab-khanal**
Changed the position to inherit from absolute to fix this issue.

Fixes #4095

### CODE REVIEW

**Review by zurfyx — COMMENTED** [review]
On the expected issue picture it looks like the TreeView is slightly decoupled from the editor itself. I would probably a padding at the end of the editor that gives enough room for these actions, WDYT?

**Comment by gaurab-khanal** [comment]
> On the expected issue picture it looks like the TreeView is slightly decoupled from the editor itself. I would probably a padding at the end of the editor that gives enough room for these actions, WDYT?

I am just a beginner who is learning different technologies and to gain more practical real world experiences I am contributing to Open-Source projects. If you think your approach can fix the issue more effectively I would be happy to work on that. But I can't get your approach how can I fix with that approach? Can you guide me?

**Comment by gaurab-khanal** [comment]
> > On the expected issue picture it looks like the TreeView is slightly decoupled from the editor itself. I would probably a padding at the end of the editor that gives enough room for these actions, WDYT?

I got it. Should I remove the previous changes and add new changes? I mean adding padding to the editor.

**Comment by zurfyx** [comment]
Thank you, I like this, just one more thing. The padding should live on the contenteditable as otherwise when clicking on it the editor loses selection. Could you iterate on this please?

**Comment by zurfyx** [comment]
> > Thank you, I like this, just one more thing. The padding should live on the contenteditable as otherwise when clicking on it the editor loses selection. Could you iterate on this please?
> 
> Can you elaborate more? As a beginner I can't understand what you are talking about.

The padding should be part of the `contenteditable` div, not the parent. This way when clicking on the padded part the selection (cursor) will move to the editor and will be able to continue typing. Currently, when I click on the 40px you added I have to click back again on the `contenteditable` to add more content

**Comment by gaurab-khanal** [comment]
> > > Thank you, I like this, just one more thing. The padding should live on the contenteditable as otherwise when clicking on it the editor loses selection. Could you iterate on this please?
> > 
> > 
> > Can you elaborate more? As a beginner I can't understand what you are talking about.
> 
> The padding should be part of the `contenteditable` div, not the parent. This way when clicking on the padded part the selection (cursor) will move to the editor and will be able to continue typing. Currently, when I click on the 40px you added I have to click back again on the `contenteditable` to add more content

I made the changes. Can you review it?

**Comment by gaurab-khanal** [comment]
@zurfyx Are you available?

**Review by zurfyx — APPROVED** [review]
LGTM, thank you for iterating on this!

**Comment by gaurab-khanal** [comment]
> LGTM, thank you for iterating on this!

You are welcome

**Pull request merged**
