### PR TITLE
Bug: Undo command after creating a Quote removes text after Quote ele…

### PR DESCRIPTION
**Pull request by iampava**
…ment (https://github.com/facebook/lexical/issues/2750)

### CODE REVIEW

**Comment by iampava** [comment]
Look like some tests are failing because of my change. Will have a look at them later today/tomorrow 👀

**Comment by fantactuka** [comment]
> Looks like some tests are failing because of my change. Will have a look at them later today/tomorrow 👀

Looks like it’s all good. Thanks for digging into it!

**Review by fantactuka — APPROVED** [review]

**Comment by thegreatercurve** [comment]
Closes #2750

**Comment by thegreatercurve** [comment]
Thanks @iampava! Much appreciated

**Pull request merged**
