### PR TITLE
fix: playground bug(floating link editor not closing with 'Escape' key

### PR DESCRIPTION
**Pull request by heesungjang**
fixed playground bug - closing the floating link editor with the "Escape" key did not work (https://github.com/facebook/lexical/issues/2758).

- previously, it did not work because the logic for the 'escape' keyDown only existed and applied to link-input (input tag). [#link](https://github.com/facebook/lexical/blob/5a1c20da44eba7968523c40f076ba6ba43fed1bd/packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx#L324)

- however, when isEditMode is false, it actually conditionally renders a different tag which is a div element.

It was not ideal to add tabindex={0} to this div element and onKeyDown. This was because the div element then had to get focused which will prevent the user from range selecting the link text or moving the cursor in between link texts.

### CODE REVIEW

**Comment by heesungjang** [comment]
> Thanks for working on it! Downside of the fix is that after pressing Escape editor loses focus (it's intentional to allow getting out of editor with keyboard only, [see here](https://github.com/facebook/lexical/blob/main/packages/lexical-rich-text/src/index.ts#L896-L908)). With that said, I think fix should also utilize KEY_ESCAPE_COMMAND listener, that if link modal is opened will close it (and return false in command handler to prevent default behaviour from the code pointer above)

thanks @fantactuka ! I will look into that approach.

**Comment by heesungjang** [comment]
Hi, @fantactuka. I have utilized KEY_ESCAPE_COMMAND to close the floating link editor. 

It prevents the default editor behavior(escape editor with escape key) if floating link editor is opened.

**Comment by heesungjang** [comment]
HI @fantactuka this is now ready for the review.

**Review by thegreatercurve — APPROVED** [review]
Sorry for the late review! This look goos to me though!

**Comment by thegreatercurve** [comment]
Closes #2758

**Pull request merged**
