### PR TITLE
fix: set cursor grab when image can be dragged

### PR DESCRIPTION
**Pull request by LuciNyan**
## Description
set cursor grab when image can be dragged. 

#### Additionally
I've tried a lot but still can't resolve the problem of not being able to set the cursor when dragging

### CODE REVIEW

**Comment by fantactuka** [comment]
Have you tried to set cursor style to document body while dragging?

**Comment by LuciNyan** [comment]
> Have you tried to set cursor style to document body while dragging?

Yes, I tried, but it didn't work.

**Comment by fantactuka** [comment]
Even with "!important"? 😯

**Comment by LuciNyan** [comment]
> Even with "!important"? 😯

Yes... This is strange. Will it work on windows? I'm curious.

**Review by fantactuka — APPROVED** [review]

**Comment by fantactuka** [comment]
> > Even with "!important"? 😯
> 
> Yes... This is strange. Will it work on windows? I'm curious.

Looks like browser forces cursor if has drag data: https://bugs.chromium.org/p/chromium/issues/detail?id=1196385

**Pull request merged**
