### PR TITLE
Add collaboration example with yjs

### PR DESCRIPTION
**Pull request by kdawgwilk**
Credit goes to @rchrd2 https://discuss.yjs.dev/t/lexical-text-editor/1087/3

### CODE REVIEW

**Comment by kdawgwilk** [comment]
link to doc page to view https://lexical-git-fork-kdawgwilk-patch-1-fbopensource.vercel.app/docs/collaboration

**Comment by kdawgwilk** [comment]
Would it be better to put this example in a `Collaboration -> React` sub section?

**Comment by acywatson** [comment]
> Would it be better to put this example in a `Collaboration -> React` sub section?

Probably, yea - given that it’s a 

> Would it be better to put this example in a `Collaboration -> React` sub section?

Yea, probably, given that it’s using the React plugin.

**Review by trueadm — APPROVED** [review]
Thanks

**Comment by trueadm** [comment]
> Yea, probably, given that it’s using the React plugin.

That's a good point. We can link to it from the main Collaboration section too.

**Review by zurfyx — APPROVED** [review]

**Comment by kdawgwilk** [comment]
Alright got that moved to a subsection of Collaboration top level section.  Or would you rather I move it to the React section and link from the Collaboration doc?

**Comment by acywatson** [comment]
> Alright got that moved to a subsection of Collaboration top level section. Or would you rather I move it to the React section and link from the Collaboration doc?

I think this is good for now - it can always be moved. Thanks again!

**Pull request merged**
