### PR TITLE
Add algolia config

### PR DESCRIPTION
**Pull request by harish-sethuraman**
I've installed algolia config and package as well. We have to apply to get algolia search
https://docsearch.algolia.com/apply/

It asks for details regarding organisation. Can someone help here? 

fixes 
- https://github.com/facebook/lexical/issues/1759

### CODE REVIEW

**Comment by acywatson** [comment]
Applied for access to Algolia, waiting for the credentials.

**Comment by harish-sethuraman** [comment]
@acywatson any updates on this?

**Comment by acywatson** [comment]
> @acywatson any updates on this?

I got an email from them, seems like a ticket is open with their support team, so it’ll probably be Monday before we get a response

**Comment by acywatson** [comment]
> > @acywatson any updates on this?
> 
> I got an email from them, seems like a ticket is open with their support team, so it’ll probably be Monday before we get a response

Update: they got back to me, but asked me to confirm that I am a maintainer and still have not sent the actual keys we need. Will keep you posted :)

**Comment by acywatson** [comment]
This should be what you need:

```
appId: YRGKJK6OMH,
apiKey: 00b99bc61a623e1abd819b1d655da918,
indexName: lexical,
```
@harish-sethuraman

**Comment by trueadm** [comment]
Thanks!

**Review by trueadm — APPROVED** [review]

**Pull request merged**
