### PR TITLE
Fix getSelectedNode logic for forward selection

### PR DESCRIPTION
**Pull request by moy2010**
Fixes `getSelectedNode` logic for forward selection.

### CODE REVIEW

**Comment by trueadm** [comment]
Can you explain why this change makes sense? As I'm struggling to understand it. Maybe a video or tests of some kind?

**Comment by moy2010** [comment]
> Can you explain why this change makes sense? As I'm struggling to understand it. Maybe a video or tests of some kind?

Sure!

You can test this by copy/pasting this in the playground:

I am a [link](http://example.com/)!

If you start selecting the word `link` starting from the letter `l`, `isLink` will be `true`, but it should stop being `true` as soon as you select the exclamation mark, since that is no longer a `LinkNode`. 

If you do the same bu by selecting the word backwards you should see the correct behaviour.

**Comment by moy2010** [comment]
As for the explanation for why this makes sense, if we take the example given above you can see that the node being selected at the end of the selection (focus) is a `TextNode`, thus the existing logic which returns the `focusNode` if `$isAtNodeEnd(anchor)` returns `true` is incorrect.

**Review by trueadm — APPROVED** [review]
Thank you for the explanation

**Pull request merged**
