### PR TITLE
website: update docusaurus and config changes

### PR DESCRIPTION
**Pull request by pranabdas**
Updated Docusaurus to latest 2.0.0-beta.20, set sidebar `hideable` and `autoCollapseCategories` to `true`.

### CODE REVIEW

**Review by zurfyx — APPROVED** [review]
LGTM, thanks! Mind fixing the conflicts?

**Comment by pranabdas** [comment]
@zurfyx should be OK now.

**Comment by pranabdas** [comment]
@zurfyx Not sure if I am doing something wrong 🤔 I cloned `lexical/main` → applied my changes to `package.json` and `docusaurus.config.js` under `packages/lexical-website-new/`. Issued `npm i`, it updated the `package-lock.json` in the project root (`packages/lexical-website-new/package-lock.json` is not changed). I guess the package-lock is the only source of test failures.

**Comment by acywatson** [comment]
> @zurfyx Not sure if I am doing something wrong 🤔 I cloned `lexical/main` → applied my changes to `package.json` and `docusaurus.config.js` under `packages/lexical-website-new/`. Issued `npm i`, it updated the `package-lock.json` in the project root (`packages/lexical-website-new/package-lock.json` is not changed). I guess the package-lock is the only source of test failures.

You're not doing anything wrong - we made a change that revealed a bug in our CI caching which is causing this error. The fix is in #2113. We'll probably ask you to rebase onto that after it's merged, if you don't mind. Thanks for your patience.

**Pull request merged**
