### PR TITLE
fix(tables): Add missing paragraph node when copying empty cells from external resources

### PR DESCRIPTION
**Pull request by vect-spasquereau**
Fixes https://github.com/facebook/lexical/issues/5662

### Issue

When copy/pasting a table from external sources (google doc, google spreadshet, e.g.), an empty cell is created with no child node :

image

### Change

Return `after` callback in `convertTableCellNodeElement` to insert paragraph if the cell is empty :

image

### CODE REVIEW

**Comment by StyleT** [comment]
Hi! Do you think this can be covered with test?

**Comment by vect-spasquereau** [comment]
hey @StyleT , I implemented a test for my fix. As table nodes are not massively covered, I added a bunch of tests for rows and cells.

**Review by zurfyx — COMMENTED** [review]
Thank you. However, the paragraph will be automatically created upon typing, which resembles the same behavior as when you type on an empty editor (only a RootNode). Do you mind expanding on the problem you're trying to solve here?

**Comment by vect-spasquereau** [comment]
@zurfyx unfortunately no, the paragraph node is not created upon typing in an empty cell 😕 It creates a text node, not a paragraph node:

image

The issue is when you focus an empty table cell node and that you press "Enter". There are some methods involved in `LexicalSelection` that are supposed to find the right position where the new paragraph should be inserted. These methods (`removeTextAndSplitBlock` and `splitNodeAtPoint`) create an infinite loop in this specific case that crashed lexical. I don't want to modify these functions because I'm not aware of the impacts it could have. Having a paragraph inside empty cells is fixing this issue.

Also, I noticed that a paragraph node was explicitely created in cells in methods like `$createTableNodeWithDimensions`, `$insertTableRow`, `$insertTableColumn`, etc. So I assumed it was the right thing to do 🙂

**Review by acywatson — APPROVED** [review]
I think this is reasonable. Will let @zurfyx confirm that he doesn't have further objections.

**Review by zurfyx — APPROVED** [review]

**Comment by vect-spasquereau** [comment]
thx 🙌

**Pull request merged**
