### PR TITLE
[lexical-playground] Feature: Highlight special strings with format

### LINKED ISSUE #6610: Feature: Highlight special strings
## Description
Maybe someone has already mentioned it somewhere, but I haven't seen anything like that.

I would like a specific string in the text to be highlighted, but I don't know what functions to use for that (if they exist).

The reason is that in the text I use e.g. actually variables in the form `[variableName]` and I would like to have them highlighted in the editor.

e.g. I have a text:
**What is Lorem Ipsum?**
Lorem Ipsum is simply _dummy_ text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever **since the 1500s**, when an unknown [printer] took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries

and I want to automatically have [printer] highlighted in the text, e.g. backgroundColor: yellow.

Thank you for any advice

### PR DESCRIPTION
**Pull request by citruscai**
## Description
This PR introduces a SpecialTextNode and its corresponding plugin, enabling automatic recognition and highlighting of specific text patterns (e.g., [variableName]) in the editor. This feature enhances the editor's functionality by visually distinguishing variable-like text, as requested in Issue #6610.

Key changes:

**SpecialTextNode**: Recognizes specific string patterns and highlights them 
**SpecialTextPlugin**: Processes any  simple text string that starts with an opening bracket and closes with a closing bracket and applies the SpecialTextNode to remove brackets and highlight the string
**Playground Integration**: Added a toggle setting in the lexical-playground to enable or disable the SpecialTextPlugin for flexibility 

Closes #6610

https://github.com/user-attachments/assets/2249fd55-0d16-43dc-a1b8-646b06b8912d

### CODE REVIEW

**Comment by etrepum** [comment]
This code fails the formatting checks, you can fix this with `npm run prettier:fix`. Normally this is taken care of by the commit hook installed by [husky](https://typicode.github.io/husky/), not sure why it's not running or installed in your local environment (it will typically install itself when you `npm install` the project).

**Comment by etrepum** [comment]
It looks like your e2e tests are failing:

```
  3 failed
    [chromium] › packages/lexical-playground/__tests__/e2e/SpecialTexts.spec.mjs:26:3 › Special Text › should handle a single special text 
    [chromium] › packages/lexical-playground/__tests__/e2e/SpecialTexts.spec.mjs:43:3 › Special Text › should handle multiple special texts 
    [chromium] › packages/lexical-playground/__tests__/e2e/SpecialTexts.spec.mjs:66:3 › Special Text › should not work when the option to use brackets for highlighting is disabled 
```

Do you know how to run these locally?

**Comment by citruscai** [comment]
> It looks like your e2e tests are failing:
> 
> ```
>   3 failed
>     [chromium] › packages/lexical-playground/__tests__/e2e/SpecialTexts.spec.mjs:26:3 › Special Text › should handle a single special text 
>     [chromium] › packages/lexical-playground/__tests__/e2e/SpecialTexts.spec.mjs:43:3 › Special Text › should handle multiple special texts 
>     [chromium] › packages/lexical-playground/__tests__/e2e/SpecialTexts.spec.mjs:66:3 › Special Text › should not work when the option to use brackets for highlighting is disabled 
> ```
> 
> Do you know how to run these locally?

i kept having an issue trying to run them locally :(  
image
was i using the right command?

**Comment by etrepum** [comment]
It looks like you need to run `npm install`. Whenever the package.json or package-lock.json changes you need to run that command. That dependency was added a few weeks ago.

Note that to run the tests you will need the dev server running in another terminal (e.g. `npm run start`)

**Comment by citruscai** [comment]
@etrepum sorry had wifi outage yesterday in area, since i made the special text feature into something you can switch on and off, how could i implement that in the test? do i need to set up a mock or something?

**Comment by etrepum** [comment]
It appears that this feature fails the collab test suite, which is run with `npm run test-e2e-chromium` (`npm run start` must be running in another terminal)

**Comment by citruscai** [comment]
> It appears that this feature fails the collab test suite, which is run with `npm run test-e2e-chromium` (`npm run start` must be running in another terminal)

the issue is that the test file is apparently too slow :( 
image
but when i put each test case in it's own indivudual file, each of them are also slow 
image
not sure of a way around this one

**Comment by etrepum** [comment]
That's not the problem. It keeps retrying because the result is incorrect, and then it times out.

**Comment by etrepum** [comment]
Were you running it with collab active?

**Comment by citruscai** [comment]
> Were you running it with collab active?

yes, should i disable collab in my tests?

**Comment by citruscai** [comment]
oh wait i may be stupid i think i understand what u mean, i was missing iscollab here
image

**Comment by citruscai** [comment]
@etrepum im running same command multiple times and it said test cases passed with no previous tests failing first, now that i ran the exam same command after pushing my code, it's now  failing :(( its like it never end 
```
PS C:\Users\Cairo\Documents\lexical> npm run test-e2e-chromium -- --debug 'packages/lexical-playground/__tests__/e2e/SpecialTexts.spec.mjs'

> @lexical/monorepo@0.20.0 test-e2e-chromium
> cross-env E2E_BROWSER=chromium playwright test --project="chromium" packages/lexical-playground/__tests__/e2e/SpecialTexts.spec.mjs


Running 3 tests using 1 worker

  ✘  1 [chromium] › packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:27:3 › Special Text › should handle a single special text (2.5m)    
  ✘  2 …m] › packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:27:3 › Special Text › should handle a single special text (retry #1) (3.0m)  ✘  3 [chromium] › packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:47:3 › Special Text › should handle multiple special texts (2.5m)   
  ✘  4 …] › packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:47:3 › Special Text › should handle multiple special texts (retry #1) (3.0m)  ✘  5 …nd\__tests__\e2e\SpecialTexts.spec.mjs:73:3 › Special Text › should not work when the option to use brackets for highlighting is disabled (2.5m)  ✘  6 …_\e2e\SpecialTexts.spec.mjs:73:3 › Special Text › should not work when the option to use brackets for highlighting is disabled (retry #1) (3.0m)

  1) [chromium] › packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:27:3 › Special Text › should handle a single special text 

    Test timeout of 150000ms exceeded while running "beforeEach" hook.

      18 | test.describe('Special Text', () => {
      19 |   test.use({shouldAllowHighlightingWithBrackets: true});
    > 20 |   test.beforeEach(({isCollab, page, shouldAllowHighlightingWithBrackets}) =>
         |        ^
      21 |     initialize({
      22 |       isCollab,
      23 |       page,

        at C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:20:8

    Error: page.waitForSelector: Test timeout of 150000ms exceeded.
    Call log:
      - waiting for locator('.tree-view-output pre') to be visible


       at packages\lexical-playground\__tests__\utils\index.mjs:164

      162 |   }
      163 |   const leftFrame = getPageOrFrame(page);
    > 164 |   await leftFrame.waitForSelector('.tree-view-output pre');
          |                   ^
      165 |   await leftFrame.evaluate(() => {
      166 |     window.lexicalEditor = document.querySelector(
      167 |       '[data-lexical-editor="true"]',

        at exposeLexicalEditor (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:164:19)
        at initialize (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:136:9)

    Retry #1 ───────────────────────────────────────────────────────────────────────────────────────

    Test timeout of 150000ms exceeded while running "beforeEach" hook.

      18 | test.describe('Special Text', () => {
      19 |   test.use({shouldAllowHighlightingWithBrackets: true});
    > 20 |   test.beforeEach(({isCollab, page, shouldAllowHighlightingWithBrackets}) =>
         |        ^
      21 |     initialize({
      22 |       isCollab,
      23 |       page,

        at C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:20:8

    Error: page.waitForSelector: Test timeout of 150000ms exceeded.
    Call log:
      - waiting for locator('.tree-view-output pre') to be visible


       at packages\lexical-playground\__tests__\utils\index.mjs:164

      162 |   }
      163 |   const leftFrame = getPageOrFrame(page);
    > 164 |   await leftFrame.waitForSelector('.tree-view-output pre');
          |                   ^
      165 |   await leftFrame.evaluate(() => {
      166 |     window.lexicalEditor = document.querySelector(
      167 |       '[data-lexical-editor="true"]',

        at exposeLexicalEditor (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:164:19)
        at initialize (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:136:9)

    attachment #1: video (video/webm) ──────────────────────────────────────────────────────────────
    test-results\e2e-SpecialTexts-Special-T-02db4-andle-a-single-special-text-chromium-retry1\video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────

  2) [chromium] › packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:47:3 › Special Text › should handle multiple special texts

    Test timeout of 150000ms exceeded while running "beforeEach" hook.

      18 | test.describe('Special Text', () => {
      19 |   test.use({shouldAllowHighlightingWithBrackets: true});
    > 20 |   test.beforeEach(({isCollab, page, shouldAllowHighlightingWithBrackets}) =>
         |        ^
      21 |     initialize({
      22 |       isCollab,
      23 |       page,

        at C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:20:8

    Error: page.waitForSelector: Test timeout of 150000ms exceeded.
    Call log:
      - waiting for locator('.tree-view-output pre') to be visible


       at packages\lexical-playground\__tests__\utils\index.mjs:164

      162 |   }
      163 |   const leftFrame = getPageOrFrame(page);
    > 164 |   await leftFrame.waitForSelector('.tree-view-output pre');
          |                   ^
      165 |   await leftFrame.evaluate(() => {
      166 |     window.lexicalEditor = document.querySelector(
      167 |       '[data-lexical-editor="true"]',

        at exposeLexicalEditor (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:164:19)
        at initialize (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:136:9)

    Retry #1 ───────────────────────────────────────────────────────────────────────────────────────

    Test timeout of 150000ms exceeded while running "beforeEach" hook.

      18 | } from '../utils/index.mjs';
      19 |
    > 20 | test.describe('Special Text', () => {
         |        ^
      21 |   test.use({shouldAllowHighlightingWithBrackets: true});
      22 |   test.beforeEach(({isCollab, page, shouldAllowHighlightingWithBrackets}) =>
      23 |     initialize({

        at C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:20:8

    Error: page.waitForSelector: Test timeout of 150000ms exceeded.
    Call log:
      - waiting for locator('.tree-view-output pre') to be visible


       at packages\lexical-playground\__tests__\utils\index.mjs:164

      162 |   }
      163 |   const leftFrame = getPageOrFrame(page);
    > 164 |   await leftFrame.waitForSelector('.tree-view-output pre');
          |                   ^
      165 |   await leftFrame.evaluate(() => {
      166 |     window.lexicalEditor = document.querySelector(
      167 |       '[data-lexical-editor="true"]',

        at exposeLexicalEditor (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:164:19)
        at initialize (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:136:9)

    attachment #1: video (video/webm) ──────────────────────────────────────────────────────────────
    test-results\e2e-SpecialTexts-Special-T-14fae-ndle-multiple-special-texts-chromium-retry1\video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────

  3) [chromium] › packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:73:3 › Special Text › should not work when the option to use brackets for highlighting is disabled

    Test timeout of 150000ms exceeded while running "beforeEach" hook.

      18 | } from '../utils/index.mjs';
      19 |
    > 20 | test.describe('Special Text', () => {
         |        ^
      21 |   test.use({shouldAllowHighlightingWithBrackets: true});
      22 |   test.beforeEach(({isCollab, page, shouldAllowHighlightingWithBrackets}) =>
      23 |     initialize({

        at C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:20:8

    Error: page.waitForSelector: Test timeout of 150000ms exceeded.
    Call log:
      - waiting for locator('.tree-view-output pre') to be visible


       at packages\lexical-playground\__tests__\utils\index.mjs:164

      162 |   }
      163 |   const leftFrame = getPageOrFrame(page);
    > 164 |   await leftFrame.waitForSelector('.tree-view-output pre');
          |                   ^
      165 |   await leftFrame.evaluate(() => {
      166 |     window.lexicalEditor = document.querySelector(
      167 |       '[data-lexical-editor="true"]',

        at exposeLexicalEditor (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:164:19)
        at initialize (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:136:9)

    Retry #1 ───────────────────────────────────────────────────────────────────────────────────────

    Test timeout of 150000ms exceeded while running "beforeEach" hook.

      18 | } from '../utils/index.mjs';
      19 |
    > 20 | test.describe('Special Text', () => {
         |        ^
      21 |   test.use({shouldAllowHighlightingWithBrackets: true});
      22 |   test.beforeEach(({isCollab, page, shouldAllowHighlightingWithBrackets}) =>
      23 |     initialize({

        at C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:20:8

    Error: page.waitForSelector: Test timeout of 150000ms exceeded.
    Call log:
      - waiting for locator('.tree-view-output pre') to be visible


       at packages\lexical-playground\__tests__\utils\index.mjs:164

      162 |   }
      163 |   const leftFrame = getPageOrFrame(page);
    > 164 |   await leftFrame.waitForSelector('.tree-view-output pre');
          |                   ^
      165 |   await leftFrame.evaluate(() => {
      166 |     window.lexicalEditor = document.querySelector(
      167 |       '[data-lexical-editor="true"]',

        at exposeLexicalEditor (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:164:19)
        at initialize (C:\Users\Cairo\Documents\lexical\packages\lexical-playground\__tests__\utils\index.mjs:136:9)

    attachment #1: video (video/webm) ──────────────────────────────────────────────────────────────
    test-results\e2e-SpecialTexts-Special-T-7ffde-or-highlighting-is-disabled-chromium-retry1\video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────

  3 failed
    [chromium] › packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:27:3 › Special Text › should handle a single special text
    [chromium] › packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:47:3 › Special Text › should handle multiple special texts
    [chromium] › packages\lexical-playground\__tests__\e2e\SpecialTexts.spec.mjs:73:3 › Special Text › should not work when the option to use brackets for highlighting is disabled
```

**Review by etrepum — APPROVED** [review]

**Pull request merged**
