### PR TITLE
chore: add e2e tests for maxlength plugin

### PR DESCRIPTION
**Pull request by im-adithya**
Follow up to #2467 which failed e2e

### CODE REVIEW

**Review by thegreatercurve — APPROVED** [review]
Thanks!

**Comment by thegreatercurve** [comment]
Actually looks like there may be a bug with the plugin or the E2Es. Some of these E2Es are failing legitimately.

**Review by thegreatercurve — CHANGES_REQUESTED** [review]
Actually looks like there may be a bug with the plugin or the E2Es. Some of these E2Es are failing legitimately.

**Review by fantactuka — APPROVED** [review]

**Comment by fantactuka** [comment]
Somehow messed up with tabs and pressed approve in a wrong one 🤷‍♂️

**Comment by im-adithya** [comment]
Fixed! I wasn't using focusEditor in collab mode which caused the error.
The tests are still failing though but because of another issue...
I don't understand why this is happening:
```
-   <span data-lexical-text="true">lorem ipsum dolor sit amet, c</span>
+   <span data-lexical-text="true">lorem ipsum dolor sit amet, c&nbsp;</span>
```
This same test was passing before I added the `focusEditor` line ([check here](https://github.com/facebook/lexical/runs/6972866135)) but is failing [above](https://github.com/facebook/lexical/runs/7005622566).

But I can't seem to reproduce this in my localhost (in firefox)... And this error doesn't seem to occur in mac.

Why is this happening?

**Review by thegreatercurve — APPROVED** [review]

**Comment by acywatson** [comment]
Looks like we still have failing tests here

**Comment by im-adithya** [comment]
@acywatson @thegreatercurve ready to merge!

**Pull request merged**
