### PR TITLE
Fix image copying

### PR DESCRIPTION
**Pull request by trueadm**
Fixes copying and pasting of images using node selection

### CODE REVIEW

**Review by zurfyx — COMMENTED** [review]
Will this work for base64 images?

**Comment by fantactuka** [comment]
To @zurfyx point:
exportDOM receives editor as an argument, would it be too weird to get node's `img` DOM element and get its src property (which will include full normalized url):

Screen Shot 2022-09-14 at 4 03 56 PM

**Comment by fantactuka** [comment]
To @zurfyx point: thought it would be possible to get normalized url from node's dom element, but it's hard to get to it since it's a decorator. But can just create it in memory:
```
const image = new Image();
image.src = this.__src;
return image.src; // this will be normalized
```

**Review by acywatson — APPROVED** [review]

**Comment by zurfyx** [comment]
> To @zurfyx point: thought it would be possible to get normalized url from node's dom element, but it's hard to get to it since it's a decorator. But can just create it in memory:
> 
> ```
> const image = new Image();
> image.src = this.__src;
> return image.src; // this will be normalized
> ```

But if you do window.location.href on a base64 it will break the src no?

**Comment by Fonger** [comment]
If what we need is host, why location.href here?

**Comment by acywatson** [comment]
This won't work, per the comments. We need to fix it some other way.

**Pull request closed without merging**
