### PR TITLE
Fix table cell height

### PR DESCRIPTION
**Pull request by always-maap**
fixes: #1741

### CODE REVIEW

**Comment by acywatson** [comment]
@tylerjbainbridge can you take a look?

**Comment by tylerjbainbridge** [comment]
@always-maap can you attach some images of what it looks like? This seems like a good solution for now, but in the future we'll want it to auto size because the font size is determined from the theme and not a static number.

**Review by tylerjbainbridge — APPROVED** [review]

**Comment by always-maap** [comment]
> 
sure. I will give it a try later

before:
2022-04-15-233958_1920x1080_scrot
after:
2022-04-15-234015_1920x1080_scrot

**Comment by tylerjbainbridge** [comment]
Looks good to me!

**Pull request merged**
