### PR TITLE
Add list plugin example

### PR DESCRIPTION
**Pull request by akmarzhan1**
- [x] created a CodeSandbox example for the list plugin [here](https://codesandbox.io/s/lexical-list-plugin-example-00d642)
- [x] added a new page and the example on the website (under “/docs/demos/plugins/lists”)

image

Issue https://github.com/facebook/lexical/issues/2886

### CODE REVIEW

**Comment by akmarzhan1** [comment]
I have only added the bullet list and numbered list because there were some issues with the checklist (although I imported all of the necessary components, checklists were showing up as bullet lists) and I wasn't sure whether I needed to add the examples from the list plugin only or also from the checklist plugin. 

Let me know if I need to fix anything.

**Comment by fantactuka** [comment]
> I have only added the bullet list and numbered list because there were some issues with the checklist (although I imported all of the necessary components, checklists were showing up as bullet lists) and I wasn't sure whether I needed to add the examples from the list plugin only or also from the checklist plugin.

Checklist requires [some css](https://github.com/facebook/lexical/blob/main/packages/lexical-playground/src/themes/PlaygroundEditorTheme.css#L319) to render "checkbox"

**Review by acywatson — APPROVED** [review]
Not sure about the package-lock change - did you add a new package?

**Comment by akmarzhan1** [comment]
> Not sure about the package-lock change - did you add a new package?

Also not sure where the changes came from since I didn't add new packages. Should I revert those differences?

**Comment by akmarzhan1** [comment]
> some css

That makes sense! I totally missed these, will add and update

**Comment by akmarzhan1** [comment]
@fantactuka added the check list css and now it works:
image

@acywatson reverted the package-lock changes.

Let me know if I need to fix anything else.

**Pull request merged**
