### PR TITLE
[@lexical/playground] fix: block cursor show horizontal

### PR DESCRIPTION
**Pull request by keiseiTi**
## Description

*Describe the changes in this pull request*

fix lexical PlaygroundEditor Theme  blockCursor show

RE #6459

iShot_2024-08-01_23 11 31

### Before

*Insert relevant screenshots/recordings/automated-tests*

not need test

### After

*Insert relevant screenshots/recordings/automated-tests*

not need test

### CODE REVIEW

**Comment by potatowagon** [comment]
could we have some screenshots to highlight the differences in the before & after please?

**Comment by keiseiTi** [comment]
> could we have some screenshots to highlight the differences in the before & after please?

Before

iShot_2024-08-03_10 47 42

After

iShot_2024-08-01_23 11 31

**Review by etrepum — APPROVED** [review]
I changed the PR description because this does not close #6459 (the table cell is still deleted) but it does fix the cursor display

**Comment by ivailop7** [comment]
@etrepum, let's revert this one. The block cursor is intended to be an underline. This now brakes when you have a table as first cell and move the cursor before the table. The reason it only works for the horizontal line is because of the CSS margins.

**Comment by etrepum** [comment]
@ivailop7 It looks like it works to me? This is playground css so if a user has their own css that would make this hard to see (e.g. table border of the same color) they could change it accordingly

https://github.com/user-attachments/assets/1b4895f8-eb9a-4c41-878a-cd2b97b3224f

**Comment by etrepum** [comment]
Another RTE that I could find that supported this state had similar tall vertical cursor behavior next to a table: https://richtexteditor.com/Demos/table-support.aspx

Although this one has an underline cursor above the table
https://prosemirror-tables.netlify.app/

The other editors I could find wouldn't let you get into that selection state

**Comment by ivailop7** [comment]
> @ivailop7 It looks like it works to me? This is playground css so if a user has their own css that would make this hard to see (e.g. table border of the same color) they could change it accordingly
> 
> 
> 
> https://github.com/user-attachments/assets/1b4895f8-eb9a-4c41-878a-cd2b97b3224f
> 
> 
> 
> 

Press up from that position.

**Comment by keiseiTi** [comment]
This is the editor of Yuque (a Chinese document website), and the cursor of the horizontal line in its table looks like this.

I also tried other editor interactions and they all seemed to behave differently. So it depends on how you define the interaction.

iShot_2024-08-05_09 51 08

**Comment by turnerguo** [comment]
https://prosemirror-tables.netlify.app/
I think ProseMirror's cursor intension is much more clear.
For Horizontal Line it should be a horizontal cursor their.

**Pull request merged**
