### PR TITLE
Add `SerializedParagraphNode` type export

### PR DESCRIPTION
**Pull request by matthew-plusprogramming**

### CODE REVIEW

**Review by zurfyx — APPROVED** [review]
Thank you!

**Comment by acywatson** [comment]
You need to export it fro ParagraphNode as well, I think

**Comment by matthew-plusprogramming** [comment]
Quick question @zurfyx. The documentation says that the `SerializedLineBreak` type is not exported, is there a reason? For my use case I think I may also need to handle this type. If it's okay to export, I'll open another PR for that as well

**Comment by thegreatercurve** [comment]
@matthew-plusprogramming You need to export `SerializedParagraphNode` from `LexicalParagraphNode` as well. You can add export for `SerializedLineBreakNode` here as well.

**Comment by matthew-plusprogramming** [comment]
> @matthew-plusprogramming You need to export `SerializedParagraphNode` from `LexicalParagraphNode` as well. You can add export for `SerializedLineBreakNode` here as well.

Thanks for the response. Sorry I've been out for the last few days. The `SerializedParagraphNode` and `SerializedLineBreakNode` types are already being exported in their respective files. If I'm missing anything still, please let me know but I'll push up the `SerializedLineBreakNode` export as well then re-request review!

**Comment by matthew-plusprogramming** [comment]
Reopened with new source branch name and commit https://github.com/facebook/lexical/pull/2914

**Pull request closed without merging**
