### PR TITLE
Add mentions plugin example

### PR DESCRIPTION
**Pull request by akmarzhan1**
- [x] created a CodeSandbox example for the mentions plugin [here](https://codesandbox.io/s/lexical-mention-plugin-example-ojn42n)
- [x] added a new page and the example on the website (under “/docs/demos/plugins/mentions”)

image

Issue https://github.com/facebook/lexical/issues/2886

### CODE REVIEW

**Review by tylerjbainbridge — APPROVED** [review]
This looks great! Thank you :)

**Comment by acywatson** [comment]
Is it possible to make the iframe longer by default? You could see more of the code in IDE and scroll less maybe.

**Comment by acywatson** [comment]
> @acywatson Yep, I increased the height of the iframe, is this better or should I increase it more?

I think it's good! We can always tinker with it later.

**Comment by SalahAdDin** [comment]
Where is it? I can't find the url.

**Pull request merged**
