### PR TITLE
[lexical] Bug Fix: Fix Table formatting when no TextNodes present

### PR DESCRIPTION
**Pull request by KatsiarynaDzibrova**
## Description
Don't rely on TextNode when applying formatting for empty ParagraphNode
The initial issue was fixed in https://github.com/facebook/lexical/pull/6626, but the scenario with no TextNodes present was missed in the final version of pr

## Test plan
2 tests added

### CODE REVIEW

**Comment by ivailop7** [comment]
This is still not working for the styles - font size, font color, etc for the empty cells. Also when selecting the whole table and clicking on Bold, doesn't keep the toolbar button active, which if all cells have the applied said style should have active state.

**Comment by KatsiarynaDzibrova** [comment]
Fixed toolbar buttons in https://github.com/facebook/lexical/pull/6678

Regarding text styles: ParagraphNode does not have properties to store them right now. We will need to add new properties in ParagraphNode and new create signals in Toolbar to process the action separately for table the same way it's done with formatting now. I'd rather do this in a separate pr as this is not a small change

**Comment by ivailop7** [comment]
> Fixed toolbar buttons in #6678
> 
> Regarding text styles: ParagraphNode does not have properties to store them right now. We will need to add new properties in ParagraphNode and new create signals in Toolbar to process the action separately for table the same way it's done with formatting now. I'd rather do this in a separate pr as this is not a small change

Agreed. This PR is a great step forward.

**Review by ivailop7 — APPROVED** [review]

**Comment by ivailop7** [comment]
@etrepum could I get a second pair of eyes, if you don't mind.

**Review by etrepum — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
