### PR TITLE
feat: Developer Tools Web Extension

### PR DESCRIPTION
**Pull request by LuciNyan**
### description
During the development of extensions, if we make some changes, we often need to manually reload the entire extension through the extension's admin page and then refresh the page. This feature will help us to do the above things automatically

#2127

https://user-images.githubusercontent.com/22126563/173237629-089e6573-a16f-4b16-848b-6efec3374980.mov

### CODE REVIEW

**Comment by LuciNyan** [comment]
Hello @thegreatercurve!

This wasn't in your planning, so I'm wondering if it makes sense for me to do this, and do we need this feature?

**Comment by thegreatercurve** [comment]
> Hello @thegreatercurve!
> 
> This wasn't in your planning, so I'm wondering if it makes sense for me to do this, and do we need this feature?

@LuciNyan Thanks for working on this, but unfortunately we've already earmarked the Developer Extensions work for @noi5e as part of a fellowship scheme with Meta. There's already an initial PR for it at #2388.

Hot reloading could be a useful feature, but it probably makes more sense for @noi5e to take the lead on that work, unless you want to coordinate together.

Alternatively, if you're just looking for an opportunity to contribute, an easier option would be to look through the open Issues (there are a few tagged with "Good First Issue" if you're new) without an assignee, and then add yourself, to essentially reserve it and avoid 2 people working on the same issue at the same time.

**Comment by LuciNyan** [comment]
Hello @noi5e!

I want to know if you need this feature, and if we can work together, I hope I'm not causing you any trouble

**Comment by LuciNyan** [comment]
> > Hello @thegreatercurve!
> > This wasn't in your planning, so I'm wondering if it makes sense for me to do this, and do we need this feature?
> 
> @LuciNyan Thanks for working on this, but unfortunately we've already earmarked the Developer Extensions work for @noi5e as part of a fellowship scheme with Meta. There's already an initial PR for it at #2388.
> 
> Hot reloading could be a useful feature, but it probably makes more sense for @noi5e to take the lead on that work, unless you want to coordinate together.
> 
> Alternatively, if you're just looking for an opportunity to contribute, an easier option would be to look through the open Issues (there are a few tagged with "Good First Issue" if you're new) without an assignee, and then add yourself, to essentially reserve it and avoid 2 people working on the same issue at the same time.

Thanks for your response! <3

**Comment by noi5e** [comment]
> I want to know if you need this feature(Hot reloading), and if we can work together, I hope I'm not causing you any trouble

Hi @LuciNyan, thank you for the offer! I think I'd like to work on the project by myself for the duration of the fellowship, so I don't have to keep coordinating with a peer. But in late August when the project period ends, I'm sure there will still be plenty of opportunity to contribute and improve the browser extension.

> Alternatively, if you're just looking for an opportunity to contribute, an easier option would be to look through the open Issues (there are a few tagged with "Good First Issue" if you're new) without an assignee, and then add yourself, to essentially reserve it and avoid 2 people working on the same issue at the same time.

It looks like there are some good [first issues here](https://github.com/facebook/lexical/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) BTW

**Comment by LuciNyan** [comment]
> > I want to know if you need this feature(Hot reloading), and if we can work together, I hope I'm not causing you any trouble
> 
> Hi @LuciNyan, thank you for the offer! I think I'd like to work on the project by myself for the duration of the fellowship, so I don't have to keep coordinating with a peer. But in late August when the project period ends, I'm sure there will still be plenty of opportunity to contribute and improve the browser extension.
> 
> > Alternatively, if you're just looking for an opportunity to contribute, an easier option would be to look through the open Issues (there are a few tagged with "Good First Issue" if you're new) without an assignee, and then add yourself, to essentially reserve it and avoid 2 people working on the same issue at the same time.
> 
> It looks like there are some good [first issues here](https://github.com/facebook/lexical/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) BTW

Ok, Have a good day!

**Pull request closed without merging**
