### PR TITLE
Update Browser Extension's Vite Config

### PR DESCRIPTION
**Pull request by noi5e**
Possible prerequisite #2510 ⬅️ Look at that PR first, particularly [this](https://github.com/facebook/lexical/pull/2510#pullrequestreview-1019839566) and [this comment](https://github.com/facebook/lexical/pull/2510#discussion_r907140259)

Adjusts the `vite.config.js` to clean up the file/folder structure.

# Before
Screen Shot 2022-06-27 at 11 36 54 PM

# After
Screen Shot 2022-06-27 at 11 36 18 PM

# Next Steps
Not just aesthetic, this PR paves the way for the following changes:

1. Automatic hotloading of browser extension on changes, for faster development
2. Ability to `build` the extension with a `manifest.json` v3.0, a prerequisite to getting the extension published in Chrome & Edge stores
3. Renaming of browser extension files from `.js` to `.ts` (see comment )

---
Developer Tools Web Extension Planning Issue: #2127

### CODE REVIEW

**Comment by noi5e** [comment]
Here's a weird warning that `npm run build` throws: `Generated an empty chunk: "popup"`
Screen Shot 2022-06-27 at 11 53 08 PM

Because of `entryFileNames` here:
```
rollupOptions: {
      input: {
        background: resolve(root, 'background', 'index.js'),
        content: resolve(root, 'content', 'index.js'),
        devtools: resolve(root, 'devtools', 'index.html'),
        panel: resolve(root, 'panel', 'index.html'),
        popup: resolve(root, 'popup', 'index.html')
      },
      output: {
        entryFileNames: (chunk) => `src/${chunk.name}/index.js`
      }
    }
```

Unlike the other folders/chunks, `popup` does not contain a `.js` file, only `index.html`:
Screen Shot 2022-06-27 at 11 56 03 PM

I've been looking into the Vite/[rollup docs](https://rollupjs.org/guide/en/#outputentryfilenames) but still lost looking for alternatives or customization options... So any leads would be appreciated 🙏

**Comment by thegreatercurve** [comment]
> this



> Here's a weird warning that `npm run build` throws: `Generated an empty chunk: "popup"` Screen Shot 2022-06-27 at 11 53 08 PM
> 
> Because of `entryFileNames` here:
> 
> ```
> rollupOptions: {
>       input: {
>         background: resolve(root, 'background', 'index.js'),
>         content: resolve(root, 'content', 'index.js'),
>         devtools: resolve(root, 'devtools', 'index.html'),
>         panel: resolve(root, 'panel', 'index.html'),
>         popup: resolve(root, 'popup', 'index.html')
>       },
>       output: {
>         entryFileNames: (chunk) => `src/${chunk.name}/index.js`
>       }
>     }
> ```
> 
> Unlike the other folders/chunks, `popup` does not contain a `.js` file, only `index.html`: Screen Shot 2022-06-27 at 11 56 03 PM
> 
> I've been looking into the Vite/[rollup docs](https://rollupjs.org/guide/en/#outputentryfilenames) but still lost looking for alternatives or customization options... So any leads would be appreciated 🙏

@noi5e Does the whole app it still build correctly if you omit it from the inputs?

**Review by thegreatercurve — APPROVED** [review]
Updating this to unblock you as I'll be away for a few days. You can't merge it anyway without fixing the existing TS errors. The other files which are JS should ideally be TS as well, if this config allows that to work correctly

**Comment by noi5e** [comment]
> The other files which are JS should ideally be TS as well, if this config allows that to work correctly

Just pushed new commits, every `.js` file is now `.ts`. 

The build still works, manually tested in Chrome/Firefox/Edge.

I ran into some troubles with absolute/relative path stuff, like in this example:
```
chrome.devtools.panels.create(
  'Lexical',
  '/../../favicon-32x32.png',
  '/src/panel/index.html',
);
```

If the path is `./index.html`, the panel builds in Firefox, but not in Chrome/Edge.

If the path is `src/panel/index.html`, the panel builds in Chrome/Edge, but not in Firefox.

Also, if I put `favicon-32x32.png` in an `images` folder and have the path be relative `../../images/favicon-32x32.png`, for some reason Vite doesn't parse the URL. The icon has to be in the `public` folder.

Otherwise, this PR seems to work fine. Just have to take care of things in #2510 first, then this should be merge ready.

**Comment by noi5e** [comment]
> @noi5e Does the whole app it still build correctly if you omit it from the inputs?

If I omit `popup: resolve(root, 'popup', 'index.html')` from `vite.config.js`, the `popup` folder doesn't get included in the `build` at all!

**Comment by noi5e** [comment]
@acywatson had a suggestion [here](https://github.com/facebook/lexical/pull/2510#discussion_r910299337):

> can these be constants somewhere in a different shared module, maybe?

I thought it made sense to try an implementation of that here in this PR, which I made in the latest commit `add ES6-style import in browser extension`.

The execution is very awkward because browser extension content and background scripts do not allow ES6 `import` without [workarounds](https://medium.com/@otiai10/how-to-use-es6-import-with-chrome-extension-bd5217b9c978).

Currently the implementation *does not work* because I'm encountering a block. In `src/content/index.ts`, I use dynamic import to load the content script:

`const src = chrome.runtime.getURL('./content.ts');`

However `vite.config.js` doesn't seem to be able to parse this URL. `content.ts` is not included in the final `build`.

So I guess the question is if it's going to be worth it right now to pursue ES6 style imports and modules in the content and background scripts... And if so, any suggestions for how to update the Vite config to build this properly?

**Comment by acywatson** [comment]
> @acywatson had a suggestion [here](https://github.com/facebook/lexical/pull/2510#discussion_r910299337):
> 
> > can these be constants somewhere in a different shared module, maybe?
> 
> I thought it made sense to try an implementation of that here in this PR, which I made in the latest commit `add ES6-style import in browser extension`.
> 
> The execution is very awkward because browser extension content and background scripts do not allow ES6 `import` without [workarounds](https://medium.com/@otiai10/how-to-use-es6-import-with-chrome-extension-bd5217b9c978).
> 
> Currently the implementation _does not work_ because I'm encountering a block. In `src/content/index.ts`, I use dynamic import to load the content script:
> 
> `const src = chrome.runtime.getURL('./content.ts');`
> 
> However `vite.config.js` doesn't seem to be able to parse this URL. `content.ts` is not included in the final `build`.
> 
> So I guess the question is if it's going to be worth it right now to pursue ES6 style imports and modules in the content and background scripts... And if so, any suggestions for how to update the Vite config to build this properly?

Yea, let's not worry about it for now. Thanks for looking into it!

**Comment by noi5e** [comment]
Rebased off `main` after #2510 was merged, and undid merge conflicts.

This seems ready to merge, the only thing stopping it is unrelated CI failures.

One important thing to note is that I had to do a lot of [TS linter disabling](https://github.com/facebook/lexical/blob/66916ec74c1a3cd2042b6f10bfe010ff62b14d05/packages/lexical-devtools/src/background/index.ts#L14-L20) in `background.js` to get this to pass. This was based off @thegreatercurve's suggestion [here](https://github.com/facebook/lexical/pull/2510#discussion_r909067238):

> "cast" the types to any to remove the type checks, disable the lint warning, and one of us can then do a fix PR on top to add the types.

(I'm also currently studying up on TypeScript to see if I can give this a shot myself)

**Review by acywatson — APPROVED** [review]

**Pull request merged**
