### PR TITLE
(docs) Add existing history page to navigation

### LINKED ISSUE #6348: Bug: Unable to find "concepts/history" on the lexical website
This page here: packages/lexical-website/docs/concepts/history.md is not showing up on the lexical.dev website.

image

### PR DESCRIPTION
**Pull request by TryingToImprove**
Fixes #6348

### CODE REVIEW

**Comment by TryingToImprove** [comment]
image

Not really sure if that is the title that is expected?

**Comment by potatowagon** [comment]
> image
> 
> Not really sure if that is the title that is expected?

yea, the title is alittle verbose. feel free to edit packages/lexical-website/docs/concepts/history.md to shorten the title

**Comment by potatowagon** [comment]
after:

Screenshot 2024-07-01 at 6 35 19 PM

**Review by potatowagon — APPROVED** [review]
doc changes only, safe to merge

**Pull request merged**
