### PR TITLE
Fix a bug that caused the Node to be regenerated when editing the end of an AutoLinkNode

### LINKED ISSUE #3825: Bug: Each time a character is added to the tail, the AutoLinkNode is regenerated
Lexical version: 0.7.6

## Steps To Reproduce

1. Enter the URL.
2. Add text to the end of the URL.

## The current behavior

Each time a trailing character is added, the AutoLinkNode is regenerated.
If editing in the middle of a URL, the Node is not regenerated.

https://user-images.githubusercontent.com/40270352/216815279-af159889-1280-482d-871d-fd24d0b54e82.mov

## The expected behavior

Node is not regenerated even when editing the end of the URL.

### PR DESCRIPTION
**Pull request by Karibash**
close #3825 

https://user-images.githubusercontent.com/40270352/216878308-06bc05e5-422c-4b3e-aed9-8602ce005ee9.mov

### CODE REVIEW

**Comment by trueadm** [comment]
Looks like the AutoLink e2e tests are failing?

**Comment by acywatson** [comment]
Hmmm, on the vercel preview here: https://lexical-playground-git-fork-karibash-featur-ef48ce-fbopensource.vercel.app/

it seems like this is not working correctly. if I type in https://www.github.com, the ".com" is not part of the autolink.

**Comment by Karibash** [comment]
@acywatson 
Hmm, that seems to be an existing bug.
I can reproduce it in the [current playground](https://playground.lexical.dev/).
It seems to be a bug caused by the number of characters in the domain.
The same phenomenon can be reproduced when there is a second level domain like co.jp.

https://user-images.githubusercontent.com/40270352/219257868-cb8c1d68-9595-4cfd-9f6f-5af8fe5215c6.mov

**Comment by acywatson** [comment]
> 

Ah ok - weird, the video in the PR description seems to show it working.

**Comment by Karibash** [comment]
I found an issue reporting the above problem, but it seems to be closed.
https://github.com/facebook/lexical/issues/3546

**Comment by thegreatercurve** [comment]
Related issue aside this PR looks good to merge.

**Review by thegreatercurve — APPROVED** [review]

**Pull request merged**
