### PR TITLE
pref(lexical-playground): reduce rendering consumption by creating compositing layers

### PR DESCRIPTION
**Pull request by LuciNyan**
## Description
Reduce rendering consumption by creating compositing layers

### CODE REVIEW

**Comment by acywatson** [comment]
Not sure about this one - was there a problem here you were trying to address?

**Comment by LuciNyan** [comment]
> Not sure about this one - was there a problem here you were trying to address?

I don't think the previous implementation is a "problem", but it looks better with transform. It just moves the layer instead of reflowing it.

**Comment by zurfyx** [comment]
I believe that the point @acywatson is trying to make is whether the proposed approach has noticeable a performance win. It is correct that `translate` is the preferred approach performance-wise as opposed to `top` and `left` that will always run on CPU. However, your code becomes more complicated to understand after that. I will delegate the approval to @acywatson since he's been the first the approach this PR.

**Comment by trueadm** [comment]
This should be much smoother on mobile as they generally have decent GPU power and suffer from over constrained CPU cores. Have you done any mobile comparisons?

**Comment by acywatson** [comment]
> I believe that the point @acywatson is trying to make is whether the proposed approach has noticeable a performance win. It is correct that `translate` is the preferred approach performance-wise as opposed to `top` and `left` that will always run on CPU. However, your code becomes more complicated to understand after that. I will delegate the approval to @acywatson since he's been the first the approach this PR.

I'm fine with the translation change, but was more wondering if will-change is the right thing to use here. Generally you dpn't need to start messing with things like this unless there's an explicit performance issue you're trying to solve.

This might be a noticeable improvement on mobile - would be interesting to see the comparison.

**Review by acywatson — APPROVED** [review]

**Comment by LuciNyan** [comment]
> > I believe that the point @acywatson is trying to make is whether the proposed approach has noticeable a performance win. It is correct that `translate` is the preferred approach performance-wise as opposed to `top` and `left` that will always run on CPU. However, your code becomes more complicated to understand after that. I will delegate the approval to @acywatson since he's been the first the approach this PR.
> 
> I'm fine with the translation change, but was more wondering if will-change is the right thing to use here. Generally you dpn't need to start messing with things like this unless there's an explicit performance issue you're trying to solve.
> 
> This might be a noticeable improvement on mobile - would be interesting to see the comparison.

Hi @acywatson! I really appreciate the questions you asked. Your question made me think seriously about whether so is really worth it. I had only read in many places that transform was better than left top, but I hadn't explored the issue myself. But after trying it myself, I honestly don't see a significant difference. Can you give me some advice on testing, I really want to know if we should use transform instead of left top now, or if both are ok!

**Pull request merged**
