### PR TITLE
fix: subscript and superscript can co-exist

### PR DESCRIPTION
**Pull request by im-adithya**
Screenshot from 2022-07-01 15-30-18

### CODE REVIEW

**Comment by acywatson** [comment]
Thanks! can you try rebasing onto main to trigger a new CI run and see if we get all checks? :D

**Comment by BrianHung** [comment]
ProseMirror has a flag for this if it helps: https://prosemirror.net/docs/ref/#model.MarkSpec.excludes

**Comment by im-adithya** [comment]
@acywatson, this is ready for review!

**Comment by thegreatercurve** [comment]
Closing this for the moment as the PR is becoming a little stale and because, generally, we need to rethink how we handling storing these formats, probably moving away from byte code to just an object of string literals or a set. It should be a little less performant but much more user friendly.

**Pull request closed without merging**
