### PR TITLE
feat: Add support for gifs in lexical

### PR DESCRIPTION
**Pull request by rimildeyjsr**
**Changelog:**   
* Add a button to insert a sample gif in the insert menu
* Add a sample gif
* Add gif icon

Relates to - #1820 

**Screen recording:** 

https://user-images.githubusercontent.com/10229595/164034073-463d7fbd-d88a-496f-a133-5c055c9e9acb.mov

### CODE REVIEW

**Comment by rimildeyjsr** [comment]
> Thanks for this. How is it different from just using the gif URL on the insert image workflow though?

@trueadm - I am working on a complete feature to introduce adding gifs to the editor using the GIPHY API, where we can have a modal that displays the gifs to be selected from. 

As suggested by @zurfyx I am raising the first PR to only add a hard-coded gif:
https://github.com/facebook/lexical/issues/1820#issuecomment-1100857483

**Review by trueadm — APPROVED** [review]
Awesome, thank you! :)

**Comment by zurfyx** [comment]
That's awesome, should we make the gif a bit smaller if we're planning to delete it later? It's 2MB that will sit in the git history forever

**Comment by zurfyx** [comment]
Also, what I meant for the first PR is whether we can display the gif just like we'd use the Giphy API but no objections for this as a first PR :)

**Comment by rimildeyjsr** [comment]
@zurfyx - Optimised the gif!

I will start work on the API integration from the next PR onwards!

**Comment by wobsoriano** [comment]
Maybe this can help? https://sergiop.github.io/react-giphy-searchbox/

**Comment by joncwong** [comment]
Does this only add support for gifs in the playground and not as a plugin?

**Pull request merged**
