### PR TITLE
Added sanitizer to FloatingLinkEditor

### PR DESCRIPTION
**Pull request by heesungjang**
This is new PR for #2825, removed the package.json commit.

### CODE REVIEW

**Comment by thegreatercurve** [comment]
@heesungjang Can you add this logic into ToolbarPlugin as well?

**Comment by heesungjang** [comment]
> @heesungjang Can you add this logic into ToolbarPlugin as well?

@thegreatercurve  Sure!!

```
const insertLink = useCallback(() => {
    if (!isLink) {
      editor.dispatchCommand(TOGGLE_LINK_COMMAND, sanitizeUrl('https://'));
    } else {
      editor.dispatchCommand(TOGGLE_LINK_COMMAND, null);
    }
  }, [editor, isLink]);
```

I am assuming this is where you'd like the logic to be right?

**Comment by thegreatercurve** [comment]
> > @heesungjang Can you add this logic into ToolbarPlugin as well?
> 
> @thegreatercurve  Sure!!
> 
> ```
> const insertLink = useCallback(() => {
>     if (!isLink) {
>       editor.dispatchCommand(TOGGLE_LINK_COMMAND, sanitizeUrl('https://'));
>     } else {
>       editor.dispatchCommand(TOGGLE_LINK_COMMAND, null);
>     }
>   }, [editor, isLink]);
> ```
> 
> I am assuming this is where you'd like the logic to be right? 
> 
> 

@heesungjang Remove it from the on change function, because that will block user input and instead add it to the insertLink function in both the floating toolbar and main toolbar plugins

**Comment by heesungjang** [comment]
> @heesungjang Remove it from the on change function, because that will block user input and instead add it to the insertLink function in both the floating toolbar and main toolbar plugins

@thegreatercurve I have made a change according to your advice.

**Review by thegreatercurve — APPROVED** [review]
LGTM. Thanks @heesungjang

**Pull request merged**
