### PR TITLE
[lexical-playground] Bug Fix: Fix tests

### PR DESCRIPTION
**Pull request by AlexanderReznik**
## Description
Fixing tests from https://github.com/facebook/lexical/pull/6200

I have them passing locally in WSL so it's a bit of a guess, but I'm unifying how `click` is made

### CODE REVIEW

**Comment by potatowagon** [comment]
thanks for the quick fix

**Comment by etrepum** [comment]
I think we should probably add extended-tests to #6227 first so that the windows e2e suite runs correctly again, update this PR with main after that lands to bring in the fix, and then add the extended-tests label to this PR so we can see the full suite running and confirm that the fix works cross-platform

**Review by StyleT — APPROVED** [review]

**Comment by etrepum** [comment]
Based on the mac failures I don't think this is resolved just yet, it appears to be slight differences in size metrics (height) https://github.com/facebook/lexical/actions/runs/9322094913/job/25662413222?pr=6228

**Comment by StyleT** [comment]
Rejected in favor of #6224 

Pls fix tests and re-submit your changes.  🙌

**Pull request closed without merging**
