### PR TITLE
YouTube embed: use more privacy-friendly youtube-nocookie.com instead of youtube.com

### PR DESCRIPTION
**Pull request by AlessioGr**
Europeans will be happy!

### CODE REVIEW

**Review by zurfyx — APPROVED** [review]

**Comment by zurfyx** [comment]
Mind looking into the failing checks? Not too sure why it's failing, might be a bad rebase or something

**Comment by AlessioGr** [comment]
> LGTM, mind looking into the failing checks? Not too sure why it's failing, might be a bad rebase or something

should hopefully be good now. One test was checking for youtube.com/embed instead of youtube-nocookie.com/embed. As for this:

Arc 2023-04-07 at 22 50 03@2x

This seems to potentially be a bug with the npm run ci-check command itself. At least I cannot explain it otherwise. This is how the command is defined:

`"ci-check": "npm-run-all --parallel tsc flow prettier lint",`

When I run tsc, flow, prettier and lint one by one, everything passes successfully. Thus, this might be an issue with npm-run-all?

**Comment by AlessioGr** [comment]
Visual Studio Code 2023-04-07 at 22 54 56@2x

Running "npm run prettier" manually - no issues!

**Comment by acywatson** [comment]
> Running "npm run prettier" manually - no issues!

This is a tricky one - npm run prettier actually runs with the flag --list-different, I think. The output is confusing.

Try npm run prettier:fix and then git status to see if anything changed.

**Comment by AlessioGr** [comment]
> > Running "npm run prettier" manually - no issues!
> 
> This is a tricky one - npm run prettier actually runs with the flag --list-different, I think. The output is confusing.
> 
> Try npm run prettier:fix and then git status to see if anything changed.

Aah, I see, found the issue! Yeah, that output is confusing indeed. Should be good now!

Do you by any chance know why VS Code doesn't automatically set prettier as the default formatter when I open the project? If I set it to prettier manually, it wants to do this to the settings.json:
Visual Studio Code 2023-04-07 at 23 42 09@2x

**Comment by acywatson** [comment]
> > > Running "npm run prettier" manually - no issues!
> > 
> > 
> > This is a tricky one - npm run prettier actually runs with the flag --list-different, I think. The output is confusing.
> > Try npm run prettier:fix and then git status to see if anything changed.
> 
> Aah, I see, found the issue! Yeah, that output is confusing indeed. Should be good now!
> 
> Do you by any chance know why VS Code doesn't automatically set prettier as the default formatter when I open the project? If I set it to prettier manually, it wants to do this to the settings.json: Visual Studio Code 2023-04-07 at 23 42 09@2x

I have no idea...you can probably commit that if it'd be helpful.

**Pull request merged**
