### PR TITLE
Update supported-browsers.md

### PR DESCRIPTION
**Pull request by imhamad**

### CODE REVIEW

**Comment by fantactuka** [comment]
I don't think we officially committed to support IE11

**Comment by imhamad** [comment]
Sure, no problem! 😊

I just tested however 😉

Many thanks

From: Maksim Horbachevsky ***@***.***>
Date: Wednesday, 26 July 2023 at 12:52 AM
To: facebook/lexical ***@***.***>
Cc: Hamad ***@***.***>, Mention ***@***.***>
Subject: Re: [facebook/lexical] Update supported-browsers.md (PR #4825)

I don't think we officially committed to support IE11

**Comment by acywatson** [comment]
Thanks for the PR, but we have no interest in officially supporting IE 11. There are no automated tests for it and we don't have any way to verify all the behavior around a11y, i18n, and 3P tech that are generally guarantees of how the library works.

**Comment by imhamad** [comment]
Perfect! I got it,

Thanks 😊

From: Acy Watson ***@***.***>
Date: Wednesday, 26 July 2023 at 1:21 AM
To: facebook/lexical ***@***.***>
Cc: Hamad ***@***.***>, Mention ***@***.***>
Subject: Re: [facebook/lexical] Update supported-browsers.md (PR #4825)

Thanks for the PR, but we have no interest in officially supporting IE 11. There are no automated tests for it and we don't have any way to verify all the behavior around a11y, i18n, and 3P tech that are generally guarantees of how the library works.

**Pull request closed without merging**
