### PR TITLE
[RFC] Lexical update retain selection when no event

### PR DESCRIPTION
**Pull request by zurfyx**
You unfocus the editor, `editor._editorState._selection` retains selection, you trigger

`editor.dispatchCommand`

Selection is lost.

Doesn't feel right. This PR addresses this. 

_Putting as RFC for now as there's no tests and want to double check this wasn't intended to cover some other case._

### CODE REVIEW

**Review by thegreatercurve — APPROVED** [review]

**Comment by acywatson** [comment]
Note the failing UTs

**Comment by fantactuka** [comment]
🚢

**Comment by acywatson** [comment]
> 🚢🚢🚢

**Comment by ivailop7** [comment]
merged main into the branch, curious if this is still a legit fix, seems like one? @zurfyx

**Pull request closed without merging**
