### PR TITLE
refactor(playground): kill ts-ignore

### PR DESCRIPTION
**Pull request by agriffis**
Replace with ts-expect-error where still needed.

### CODE REVIEW

**Comment by thegreatercurve** [comment]
Thanks for this @agriffis! Would you mind fixing the conflict and I can merge this in.

**Review by thegreatercurve — APPROVED** [review]

**Comment by agriffis** [comment]
@thegreatercurve Done. Note that this commit affects a file that should actually be deleted, see https://github.com/facebook/lexical/pull/5237#issuecomment-1847165683

but merging this doesn't prevent that, it's just a question of ordering. :shrug:

**Comment by agriffis** [comment]
In fact, the reason the other PR went through cleanly was because `ts-ignore` hid the problem.

**Comment by agriffis** [comment]
Blech, I'll just update this PR to delete the file

**Comment by agriffis** [comment]
Ok all set

**Comment by agriffis** [comment]
@thegreatercurve This has two commits now so it should be clear what's going on

**Review by zurfyx — APPROVED** [review]
LGTM, thank you, commits gets squashed once the PR is landed!

**Pull request merged**
