### PR TITLE
BugFix: Prevent insertion of link of collapsed selection

### PR DESCRIPTION
**Pull request by bhavyakaria**
fix: #5305

### CODE REVIEW

**Comment by acywatson** [comment]
> Shouldn't on clicking insert link button, it should be showing the edit view where user directly inserts the link and saves?Rather than having to clink on edit button to insert the link.

Yes - the way it currently works is the most annoying thing in the entire playground app to me. You are welcome to change it in a different PR.

**Comment by bhavyakaria** [comment]
PR is ready for review

**Review by ivailop7 — APPROVED** [review]

**Comment by ivailop7** [comment]
Leaving to @acywatson on how to proceed with this one.

**Comment by acywatson** [comment]
> Leaving to @acywatson on how to proceed with this one.

Looks like we have a failing test to fix. Make sure it's not causing a regression.

**Review by acywatson — CHANGES_REQUESTED** [review]
See comment re: test

**Comment by bhavyakaria** [comment]
@acywatson a bit late but have fixed the UT 😅

**Comment by ivailop7** [comment]
This introduces an issue where if try to remove an existing link when my collapsed selection is in inside the link, it blocks the toggling off of the link.

**Comment by bhavyakaria** [comment]
@ivailop7 thanks for pointing out, will fix it

**Comment by bhavyakaria** [comment]
@ivailop7 Have fixed the delete link issue.

**Review by etrepum — COMMENTED** [review]
This seems like a good change, but I don't think it passes the current e2e test suite. @acywatson might be worth removing the request changes flag so that when/if the fixes go in here we can merge it without waiting for that flag to clear

**Comment by etrepum** [comment]
Closing this PR due to staleness! If there are new updates, please reopen the PR.

**Pull request closed without merging**
