### PR TITLE
Fix undo

### PR DESCRIPTION
**Pull request by Piechota**
When doing undo in document where some text had format != 0
Error was thrown:
```
TypeError: Cannot assign to read only property '_cachedNodes' of object '#<RangeSelection>'
    at RangeSelection.setCachedNodes 
    at ParagraphNode.getWritable 
    at ParagraphNode.setTextFormat 
    at reconcileParagraphFormat 
    at $reconcileChildrenWithDirection 
 ```
Basically editorState is readOnly at this point, but we try to write to ParagraphNode when text's format is different from paragraph.
I have copied solution from `reconcileBlockDirection`

### CODE REVIEW

**Comment by Sahejkm** [comment]
Hi [Piechota](https://github.com/Piechota), 
- could we add the screenshots / videos to replicate this issue ? Thanks !
- we should also add a test for this

**Review by Sahejkm — APPROVED** [review]

**Comment by Piechota** [comment]
@Sahejkm I will add tests later this week
as for screenshot/video 
there isn't much to show with those. 
Set content with editor.setEditorState() (I missed that part in description and this might be the reason why I don't see this on playground) -> type something -> ctrl+z = error if there was TextNode with format != 0

Tbh I don't understand exactly where this error is coming from, but there is readOnly check in `reconcileBlockDirection` too and my guess is it was for the same error.

**Comment by Sahejkm** [comment]
> Tbh I don't understand exactly where this error is coming from (what makes editorState to be readOnly), but there is readOnly check in `reconcileBlockDirection` too and my guess is it was for the same error.

It would be great to get some steps to replicate the crash to understand the issue and fix better

**Comment by Piechota** [comment]
Small update.
I couldn't reproduce this with simple unit test.
So either I am doing something wrong (most likely) or it has something to do with input method.
I will have to investigate further.

**Comment by etrepum** [comment]
Closing this PR due to staleness! If there are new updates, please reopen the PR.

**Pull request closed without merging**
