### PR TITLE
Node fork modules & moduleResolution bundler

### LINKED ISSUE #4160: Support for `bundler` `moduleResolution` in TypeScript 5.0
This is a request for updating `lexical` to TS 5.0, and making sure it supports the new `bundler` `moduleResolution`.

After upgrading a project to [TS5](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/), we switched to using the new [`bundler` `moduleResolution` strategy](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler).

I noticed that running `tsc` resulted in the following errors in `lexical` (which is currently on TS `^4.6.4`):

```bash
$ npm run typecheck

> typecheck
> tsc

node_modules/@lexical/list/formatList.d.ts:9:40 - error TS7016: Could not find a declaration file for module './'. '~/exampleProject/node_modules/@lexical/list/LexicalList.js' implicitly has an 'any' type.
9 import { ListItemNode, ListNode } from './';
                                         ~~~~

node_modules/@lexical/list/utils.d.ts:9:40 - error TS7016: Could not find a declaration file for module './'. '~/exampleProject/node_modules/@lexical/list/LexicalList.js' implicitly has an 'any' type.
9 import { ListItemNode, ListNode } from './';
                                         ~~~~

node_modules/@lexical/table/LexicalTableUtils.d.ts:10:50 - error TS7016: Could not find a declaration file for module '.'. '~/exampleProject/node_modules/@lexical/table/LexicalTable.js' implicitly has an 'any' type.
10 import { InsertTableCommandPayloadHeaders } from '.';
                                                    ~~~

node_modules/lexical/LexicalNode.d.ts:10:29 - error TS7016: Could not find a declaration file for module '.'. '~/exampleProject/node_modules/lexical/Lexical.js' implicitly has an 'any' type.
10 import { ElementNode } from '.';
                               ~~~

node_modules/lexical/LexicalNormalization.d.ts:8:47 - error TS7016: Could not find a declaration file for module '.'. '~/exampleProject/node_modules/lexical/Lexical.js' implicitly has an 'any' type.
8 import type { RangeSelection, TextNode } from '.';
                                                ~~~

node_modules/lexical/LexicalSelection.d.ts:13:26 - error TS7016: Could not find a declaration file for module '.'. '~/exampleProject/node_modules/lexical/Lexical.js' implicitly has an 'any' type.
13 import { TextNode } from '.';
                            ~~~

node_modules/lexical/LexicalUtils.d.ts:14:59 - error TS7016: Could not find a declaration file for module '.'. '~/exampleProject/node_modules/lexical/Lexical.js' implicitly has an 'any' type.
14 import { DecoratorNode, ElementNode, LineBreakNode } from '.';
                                                             ~~~

node_modules/lexical/nodes/LexicalElementNode.d.ts:11:26 - error TS7016: Could not find a declaration file for module '../'. '~/exampleProject/node_modules/lexical/Lexical.js' implicitly has an 'any' type.
11 import { TextNode } from '../';
                            ~~~~~

Found 8 errors in 8 files.

Errors  Files
        1  node_modules/@lexical/list/formatList.d.ts:9
        1  node_modules/@lexical/list/utils.d.ts:9
        1  node_modules/@lexical/table/LexicalTableUtils.d.ts:10
        1  node_modules/lexical/LexicalNode.d.ts:10
        1  node_modules/lexical/LexicalNormalization.d.ts:8
        1  node_modules/lexical/LexicalSelection.d.ts:13
        1  node_modules/lexical/LexicalUtils.d.ts:14
        1  node_modules/lexical/nodes/LexicalElementNode.d.ts:11
```

We found that adding `"types": "./index.d.ts",` to the package.json of the libraries used worked as a temporary solution for most errors except one.

This error wasn't fixed by that, and reverting `moduleResolution` to `node` didn't help either. Deleting `/` in the path did:

```bash
node_modules/lexical/nodes/LexicalElementNode.d.ts:11:26 - error TS7016: Could not find a declaration file for module '../'. '~/exampleProject/node_modules/lexical/Lexical.js' implicitly has an 'any' type.
11 import { TextNode } from '../';
```

https://github.com/facebook/lexical/blob/52af9c426ba8e6c8832254b116b6ee32be3cc26d/packages/lexical/src/nodes/LexicalElementNode.ts#L20

Lexical version: 0.9.0

## The current behavior
An error output is thrown by `tsc` when using `lexical` in a TS5 project.

## The expected behavior
All type checks to be successful with no errors.

### LINKED ISSUE #5117: Bug: return types of methods are not resolved by typescript
Lexical version: 0.12.2

## Steps To Reproduce

1. Set `moduleResolution` to something other than "node" ("Bundler" in my case) in tsconfig.json's compilerOptions

Link to code example: [stackblitz](https://stackblitz.com/edit/vitejs-vite-h2jpdu?file=src%2FApp.tsx)

## The current behavior

Some of the methods on lexical objects have return type `any`.

image

I know it is possible to cast it but I believe it is better to get to the root cause of this.

## The expected behavior

Those methods should have proper return type.

image

### LINKED ISSUE #5710: Bug: some types are imported as any
Lexical version: 0.13.1 the latest

## Steps To Reproduce

1. type assertion to `PointType` from `lexical`
2. call getNode() method.
3. typescript fails to parse correct return type, instead it shows `any`

It happens when import the lexical from npm.
It works well on the code base this repo.

## The current behavior
image

## The expected behavior
image

### LINKED ISSUE #5783: Bug: peerDependencies from monorepo packages cause npm resolution errors
Lexical version: All versions since #[1396](https://github.com/facebook/lexical/pull/1396) through at least v0.14.2

## Steps To Reproduce

1. Create a package.json that depends on an older version of lexical, with at least one associated package from the monorepo that uses peerDependencies, and install it to create an initial package-lock.json e.g. `npm install lexical@0.14.1 @lexical/react@0.14.1`
2. Attempt to upgrade to a newer version of lexical, e.g. `npm install lexical@latest @lexical/react@latest` and get a resolution failure

Link to code example:

https://github.com/facebook/lexical/tree/main/examples/react-rich (or any of the other examples)

## The current behavior

<details>
<summary>
Dependency resolution fails with an error
</summary>

```
# npm resolution error report

While resolving: @lexical/react-rich-example@0.14.2
Found: @lexical/react@0.13.1
node_modules/@lexical/react
  @lexical/react@"0.14.2" from the root project

Could not resolve dependency:
@lexical/react@"0.14.2" from the root project

Conflicting peer dependency: lexical@0.14.2
node_modules/lexical
  peer lexical@"0.14.2" from @lexical/react@0.14.2
  node_modules/@lexical/react
    @lexical/react@"0.14.2" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

</details>

## The expected behavior

npm install succeeds and updates the lexical packages.

Per the node blog on peerDependencies https://nodejs.org/en/blog/npm/peer-dependencies -

> One piece of advice: peer dependency requirements, unlike those for regular dependencies, should be lenient. You should not lock your peer dependencies down to specific patch versions. It would be really annoying if one Chai plugin peer-depended on Chai 1.4.1, while another depended on Chai 1.5.0, simply because the authors were lazy and didn't spend the time figuring out the actual minimum version of Chai they are compatible with.

I think it doesn't really make sense in practice to use peerDependencies with all of these packages being updated in lock-step, and likely having interdependencies that are not based on the stable public API. Outside of the monorepo, when packages are not updated in lock-step, it would likely make sense to use peerDependencies on lexical and its associated monorepo packages (although at a glance I haven't found any lexical community packages doing this correctly!)

[Discord thread](https://discord.com/channels/953974421008293909/953974421486436393/1223334819963080734)

### PR DESCRIPTION
**Pull request by etrepum**
Create a separate set of esm fork modules specifically for node that use top-level await. These should work with node >= 14.8 (for SSR) but not cause problems for bundlers that can't handle them.

The reason to do this would be to save a bit of startup time and memory when running Lexical directly in a Node.js environment (SSR, headless, etc.). Otherwise, since tree-shaking isn't done when executing directly, both dev and prod get loaded.

Closes #5716 (those commits are cherry-picked into here)
Fixes #5710 via #5716
Fixes #5117 via #5716
Fixes #4160 via #5716
Fixes #5783 (removes inter-package monorepo peerDependencies)

### CODE REVIEW

**Comment by 2wheeh** [comment]
Hi, should `types` entry be `index.d.ts` ? 
I thought we have `index.d.ts` as an entry instead of `Lexical***.d.ts` .

i.e.
스크린샷 2024-03-28 오전 11 04 01

Sorry if it's a silly question. I feel https://github.com/facebook/lexical/pull/5716 needs some changes after seeing this...

**Comment by etrepum** [comment]
That's an issue with this draft PR, the other one did not have an exports entry for '.'

**Comment by etrepum** [comment]
Sorry didn't look up which PR you were referring to, I was talking about the state before this draft PR. I haven't seen what you've been working on yet.

**Comment by 2wheeh** [comment]
I closed #5716 ! 

btw, commits from #5716 have never got successful with `e2e-collab-windows (18.18.0, firefox)`.
I know some e2e-collab tests are flaky sometimes but it seems unusual... It always ends up being timed out. 

maybe due to updating `y-websocket` ?

**Comment by etrepum** [comment]
@2wheeh I'll take a look at that test, but not sure how successful I will be at reproducing it since I'm on macOS

**Comment by 2wheeh** [comment]
@etrepum Thanks. I was not able to reproduce for the same reason as well...
I was told @acywatson would double check this before merging anyways.

**Comment by etrepum** [comment]
I suspect these are just bad e2e tests that are failing because something about firefox is slower (maybe due to y-websocket!), I did manage to fire up an old gaming pc and install node to run these tests and they fail locally but the chromium ones succeed. This sort of test code looks particularly suspicious:

```typescript
  test('Can autocomplete a word', async ({page, isPlainText}) => {
    await focusEditor(page);
    await page.keyboard.type('Sort by alpha');
    await sleep(500);
    await assertHTML(...);
```

**Review by ivailop7 — COMMENTED** [review]
These are quite pervasive changes, need @acywatson @zurfyx @fantactuka as well, especially for the y-websocket ones. The plan is still to potentially merge before end of next week, since I'm planning on doing another release next friday.

**Comment by etrepum** [comment]
I think that #5788 should address the problems with the collab tests 🤞

**Review by ivailop7 — APPROVED** [review]

**Pull request merged**
