### PR TITLE
[Lexical] Add flow for eslint

### PR DESCRIPTION
**Pull request by Sahejkm**
add flow for eslint

### CODE REVIEW

**Review by etrepum — COMMENTED** [review]
LGTM, this is the fix for the script that generated this incorrectly if you want to add that as well (diff updated with correct regex)

```diff
diff --git a/scripts/update-flowconfig.js b/scripts/update-flowconfig.js
index be35f36d..81c82d4c 100644
--- a/scripts/update-flowconfig.js
+++ b/scripts/update-flowconfig.js
@@ -23,7 +23,7 @@ const BLOCK_REGEX =
 
 function flowTemplate(wwwName) {
   return (
-    headerTemplate.replace(/^( \*\/)$/m, '* @flow strict\n$1') +
+    headerTemplate.replace(/^( \*\/)$/m, ' * @flow strict\n$1') +
     `
 /**
  * ${wwwName}
@@ -59,22 +59,7 @@ function updateFlowconfig(flowconfigPath = './.flowconfig') {
     const resolveRelative = (...subPaths) =>
       '<PROJECT_ROOT>/' +
       path.relative(configDir, pkg.resolve(...subPaths)).replace(/^(?!\.)/, '');
-    if (pkg.isPrivate()) {
-      if (pkg.getDirectoryName() !== 'shared') {
-        continue;
-      }
-      if (process.env.TODO_DOES_WWW_NEED_SHARED_FILES === '1') {
-        // Do these even work? These .js files aren't on disk and `npm run flow`
-        // passes without them. Code is left in for demonstration purposes if
-        // this is needed for www.
-        for (const {name, sourceFileName} of pkg.getPrivateModuleEntries()) {
-          emit(
-            name,
-            resolveRelative('src', sourceFileName.replace(/\.tsx?$/, '.js')),
-          );
-        }
-      }
-    } else {
+    if (!pkg.isPrivate()) {
       for (const name of pkg.getExportedNpmModuleNames()) {
         const wwwName = npmToWwwName(name);
         const flowFile = `${wwwName}.js.flow`;
@@ -85,6 +70,7 @@ function updateFlowconfig(flowconfigPath = './.flowconfig') {
           console.log(
             `Creating boilerplate ${resolvedFlowFile.replace(/^[^/]+\//, '')}`,
           );
+          fs.mkdirsSync(path.dirname(flowFilePath));
           fs.writeFileSync(flowFilePath, flowTemplate(wwwName));
         }
       }
```

**Comment by etrepum** [comment]
er, hold off on that diff, I just tested it again and the regex is wrong 🤦  will post the correct tested diff shortly

**Comment by etrepum** [comment]
Just updated the diff above with the corrected regex, sorry about that! Early here :)

**Comment by Sahejkm** [comment]
thanks Bob for the update on the script :)

**Review by zurfyx — APPROVED** [review]

**Pull request merged**
