### PR TITLE
Bumped actions/checkout, actions/cache, actions/setup-node to v3

### PR DESCRIPTION
**Pull request by ghousemohamed**
Bumps the following actions to latest versions:

`actions/checkout@v2` => `actions/checkout@v3`
`actions/setup-node@v2` => `actions/setup-node@v3`
`actions/cache@v2` => `actions/cache@v3`

### CODE REVIEW

**Comment by ghousemohamed** [comment]
Signed the CLA, but the check is still failing.

**Review by zurfyx — APPROVED** [review]
Looks like a reasonable upgrade even if I'm unable to tell how well the CI will work with a new version Node (or maybe other changes?) once this is merged

> Signed the CLA, but the check is still failing.

Make sure your email has been previously registered on your GitHub account

**Comment by ghousemohamed** [comment]
@zurfyx Yes, the email I've used in the CLA is the same as the one linked to my GitHub profile.

**Comment by zurfyx** [comment]
> @zurfyx Yes, the email I've used in the CLA is the same as the one linked to my GitHub profile.

Looks like you can merge now!

**Comment by ghousemohamed** [comment]
> > @zurfyx Yes, the email I've used in the CLA is the same as the one linked to my GitHub profile.
> 
> Looks like you can merge now!

@zurfyx Sorry, I'm not able to merge because I do not have write access.

**Pull request merged**
