### PR TITLE
fix(code-block): move to start/move to end

### PR DESCRIPTION
**Pull request by LuciNyan**
### Description
Two new commands `MOVE_TO_START` and `MOVE_TO_END` have been added so as not to interfere with the previous callbacks receiving `KEY_ARROW_LEFT_COMMAND` and `KEY_ARROW_RIGHT_COMMAND`.

### Related Issues 📦
#1185

https://user-images.githubusercontent.com/22126563/170096068-d36d962d-5053-4019-9438-cc3445ef933c.mov

### CODE REVIEW

**Review by trueadm — APPROVED** [review]
This is awesome. Thank you! :)

**Comment by LuciNyan** [comment]
Hello @trueadm.

Could you please take a look this issue when you have time? It looks like there may be some environmental issues here that are causing the e2e test to fail.

Thanks <3

image

**Comment by acywatson** [comment]
> Hello @trueadm.
> 
> Could you please take a look this issue when you have time? It looks like there may be some environmental issues here that are causing the e2e test to fail.
> 
> Thanks <3
> 
> image

These failures are due to systemic CI issues, not related to your PR. I am re-running the failed workflows and we can merge once they pass.

**Comment by LuciNyan** [comment]
Thanks @acywatson ! <3

**Pull request merged**
