### PR TITLE
Add a function to create a LinkMatcher based on a RegExp

### PR DESCRIPTION
**Pull request by Karibash**
close: #3940

### CODE REVIEW

**Review by acywatson — APPROVED** [review]

**Comment by fantactuka** [comment]
Should we export factory function instead that will accept reg exp? There's a lot of url/email patterns and apps are often very sensitive about it

**Comment by acywatson** [comment]
> Should we export factory function instead that will accept reg exp? There's a lot of url/email patterns and apps are often very sensitive about it

Yea, this might be a good idea. I was hesitant about this change for the same reason. We are getting into the business of maintaining reg ex patterns that are notoriously fickle. At the same time, it's nice for users to have something that usually works by default, and they can always eject and do their own pattern.

Factory function seems like a good idea, regardless

**Comment by Karibash** [comment]
Is it like exporting a factory function like the one below?
```ts
function createLinkMatcherWithRegExp(
  regExp: RegExp,
  urlTransformer: (text: string) => string = (text) => text,
) {
  return (text: string) => {
    const match = regExp.exec(text);
    if (match === null) return null;
    return {
      index: match.index,
      length: match[0].length,
      text: match[0],
      url: urlTransformer(text),
    };
  };
}
```

**Comment by Karibash** [comment]
@fantactuka @acywatson 
I have fixed it, please review.

**Review by acywatson — APPROVED** [review]
Yea, this looks right, thanks!

**Pull request merged**
