### PR TITLE
fix-typo in EquationsPlugins

### PR DESCRIPTION
**Pull request by alajillo**
i found typo in EquationsPlugin.js.

### CODE REVIEW

**Review by zurfyx — APPROVED** [review]

**Comment by trueadm** [comment]
@alajillo I see there's a merge conflict, if you could please resolve that, we can merge your PR :)

**Comment by alajillo** [comment]
@trueadm thanks :)

**Comment by alajillo** [comment]
@trueadm  i've resolved merge conflicts but there are some problem in e2e-test. how can i fix it?

**Comment by zurfyx** [comment]
> @trueadm i've resolved merge conflicts but there are some problem in e2e-test. how can i fix it?

Seems like a bad run (on our side). Thank you!

**Pull request merged**
