### PR TITLE
fix: draggable block icon is invisible in read-only mode

### PR DESCRIPTION
**Pull request by karam-qaoud**

### CODE REVIEW

**Review by zurfyx — APPROVED** [review]
Thank you Karam! Glad to see you around 😃

**Review by thegreatercurve — APPROVED** [review]

**Comment by thegreatercurve** [comment]
Thanks @karam-qaoud! Hope everything is well.

**Comment by karam-qaoud** [comment]
@zurfyx @thegreatercurve Thanks! I hope you guys are doing well ❤️

**Comment by karam-qaoud** [comment]
Please feel free to merge since I don't have write access 😅

**Pull request merged**
