### PR TITLE
Fix `const CAN_USE_BEFORE_INPUT`

### PR DESCRIPTION
**Pull request by imageck**
Test the availability of `getTargetRanges()` as a property on `InputEvent`'s prototype

### CODE REVIEW

**Review by zurfyx — APPROVED** [review]
LGTM, I wonder what motivated you to change this line. Is it performance?

**Comment by imageck** [comment]
> LGTM, I wonder what motivated you to change this line. Is it performance?

Yes, but it's also not a good style or practice objectively. There is absolutely no reason for doing that.

**Comment by ivailop7** [comment]
@imageck only the CLA is missing and it's ready to merge.

**Comment by thegreatercurve** [comment]
@imageck Would you mind adding signing the CLA so we can merge this PR?

**Comment by zurfyx** [comment]
Inactivity cleanup. Feel free to reopen

**Pull request closed without merging**
