### PR TITLE
Add $ prefix to updateToolbar on react-rich example

### PR DESCRIPTION
**Pull request by 2wheeh**
Should this be with $ prefix ?

### CODE REVIEW

**Comment by potatowagon** [comment]
related discussion about $ prefix: https://github.com/facebook/lexical/discussions/1800#discussioncomment-2585547

**Review by potatowagon — APPROVED** [review]
makes sense to prefix $ since the fn touches the editor state

cross reference: $ is prefixed here in a similar usecase: https://github.com/facebook/lexical/blame/a951969b63e03717ee28f30fdae15a7805e94bd8/packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx#L549

theres also https://github.com/facebook/lexical/blob/a951969b63e03717ee28f30fdae15a7805e94bd8/packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx#L295

which could benefit from this change too

lgtm!

**Comment by potatowagon** [comment]
A | B | C |
---------- | ----------- | -----------
1 | 2 | 3
4 | `5` | `6`
new <br/>line | **bold** | *italic*
new <br/> line <br/>  new <br/> line | 10 | 11

^ copy directly into lexical

## Before

Screenshot 2024-04-15 at 10 05 45 PM

## After

Screenshot 2024-04-15 at 10 06 16 PM

**Comment by 2wheeh** [comment]
@potatowagon hi, looks like your last comment might have landed on the wrong PR 😋

**Comment by potatowagon** [comment]
> @potatowagon hi, looks like your last comment might have landed on the wrong PR 😋

haha oh dear silly me thanks for letting me know! 😅

**Review by StyleT — APPROVED** [review]

**Pull request merged**
